// Code generated by ent, DO NOT EDIT.

package usermodeltokendailylimitconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldUserID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldModel, v))
}

// DailyLimitTokens applies equality check predicate on the "daily_limit_tokens" field. It's identical to DailyLimitTokensEQ.
func DailyLimitTokens(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldDailyLimitTokens, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNotIn(FieldUserID, vs...))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldContainsFold(FieldModel, v))
}

// DailyLimitTokensEQ applies the EQ predicate on the "daily_limit_tokens" field.
func DailyLimitTokensEQ(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldEQ(FieldDailyLimitTokens, v))
}

// DailyLimitTokensNEQ applies the NEQ predicate on the "daily_limit_tokens" field.
func DailyLimitTokensNEQ(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNEQ(FieldDailyLimitTokens, v))
}

// DailyLimitTokensIn applies the In predicate on the "daily_limit_tokens" field.
func DailyLimitTokensIn(vs ...int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldIn(FieldDailyLimitTokens, vs...))
}

// DailyLimitTokensNotIn applies the NotIn predicate on the "daily_limit_tokens" field.
func DailyLimitTokensNotIn(vs ...int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNotIn(FieldDailyLimitTokens, vs...))
}

// DailyLimitTokensGT applies the GT predicate on the "daily_limit_tokens" field.
func DailyLimitTokensGT(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGT(FieldDailyLimitTokens, v))
}

// DailyLimitTokensGTE applies the GTE predicate on the "daily_limit_tokens" field.
func DailyLimitTokensGTE(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldGTE(FieldDailyLimitTokens, v))
}

// DailyLimitTokensLT applies the LT predicate on the "daily_limit_tokens" field.
func DailyLimitTokensLT(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLT(FieldDailyLimitTokens, v))
}

// DailyLimitTokensLTE applies the LTE predicate on the "daily_limit_tokens" field.
func DailyLimitTokensLTE(v int64) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldLTE(FieldDailyLimitTokens, v))
}

// DailyLimitTokensIsNil applies the IsNil predicate on the "daily_limit_tokens" field.
func DailyLimitTokensIsNil() predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldIsNull(FieldDailyLimitTokens))
}

// DailyLimitTokensNotNil applies the NotNil predicate on the "daily_limit_tokens" field.
func DailyLimitTokensNotNil() predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.FieldNotNull(FieldDailyLimitTokens))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserModelTokenDailyLimitConfig) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserModelTokenDailyLimitConfig) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserModelTokenDailyLimitConfig) predicate.UserModelTokenDailyLimitConfig {
	return predicate.UserModelTokenDailyLimitConfig(sql.NotPredicates(p))
}
