// Code generated by ent, DO NOT EDIT.

package groupcandidatetokendailylimitconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldGroupID, v))
}

// RouteAlias applies equality check predicate on the "route_alias" field. It's identical to RouteAliasEQ.
func RouteAlias(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldRouteAlias, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldUpstreamModel, v))
}

// DailyLimitTokens applies equality check predicate on the "daily_limit_tokens" field. It's identical to DailyLimitTokensEQ.
func DailyLimitTokens(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldDailyLimitTokens, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNotIn(FieldGroupID, vs...))
}

// RouteAliasEQ applies the EQ predicate on the "route_alias" field.
func RouteAliasEQ(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldRouteAlias, v))
}

// RouteAliasNEQ applies the NEQ predicate on the "route_alias" field.
func RouteAliasNEQ(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNEQ(FieldRouteAlias, v))
}

// RouteAliasIn applies the In predicate on the "route_alias" field.
func RouteAliasIn(vs ...string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldIn(FieldRouteAlias, vs...))
}

// RouteAliasNotIn applies the NotIn predicate on the "route_alias" field.
func RouteAliasNotIn(vs ...string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNotIn(FieldRouteAlias, vs...))
}

// RouteAliasGT applies the GT predicate on the "route_alias" field.
func RouteAliasGT(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGT(FieldRouteAlias, v))
}

// RouteAliasGTE applies the GTE predicate on the "route_alias" field.
func RouteAliasGTE(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGTE(FieldRouteAlias, v))
}

// RouteAliasLT applies the LT predicate on the "route_alias" field.
func RouteAliasLT(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLT(FieldRouteAlias, v))
}

// RouteAliasLTE applies the LTE predicate on the "route_alias" field.
func RouteAliasLTE(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLTE(FieldRouteAlias, v))
}

// RouteAliasContains applies the Contains predicate on the "route_alias" field.
func RouteAliasContains(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldContains(FieldRouteAlias, v))
}

// RouteAliasHasPrefix applies the HasPrefix predicate on the "route_alias" field.
func RouteAliasHasPrefix(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldHasPrefix(FieldRouteAlias, v))
}

// RouteAliasHasSuffix applies the HasSuffix predicate on the "route_alias" field.
func RouteAliasHasSuffix(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldHasSuffix(FieldRouteAlias, v))
}

// RouteAliasEqualFold applies the EqualFold predicate on the "route_alias" field.
func RouteAliasEqualFold(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEqualFold(FieldRouteAlias, v))
}

// RouteAliasContainsFold applies the ContainsFold predicate on the "route_alias" field.
func RouteAliasContainsFold(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldContainsFold(FieldRouteAlias, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// DailyLimitTokensEQ applies the EQ predicate on the "daily_limit_tokens" field.
func DailyLimitTokensEQ(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldEQ(FieldDailyLimitTokens, v))
}

// DailyLimitTokensNEQ applies the NEQ predicate on the "daily_limit_tokens" field.
func DailyLimitTokensNEQ(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNEQ(FieldDailyLimitTokens, v))
}

// DailyLimitTokensIn applies the In predicate on the "daily_limit_tokens" field.
func DailyLimitTokensIn(vs ...int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldIn(FieldDailyLimitTokens, vs...))
}

// DailyLimitTokensNotIn applies the NotIn predicate on the "daily_limit_tokens" field.
func DailyLimitTokensNotIn(vs ...int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNotIn(FieldDailyLimitTokens, vs...))
}

// DailyLimitTokensGT applies the GT predicate on the "daily_limit_tokens" field.
func DailyLimitTokensGT(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGT(FieldDailyLimitTokens, v))
}

// DailyLimitTokensGTE applies the GTE predicate on the "daily_limit_tokens" field.
func DailyLimitTokensGTE(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldGTE(FieldDailyLimitTokens, v))
}

// DailyLimitTokensLT applies the LT predicate on the "daily_limit_tokens" field.
func DailyLimitTokensLT(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLT(FieldDailyLimitTokens, v))
}

// DailyLimitTokensLTE applies the LTE predicate on the "daily_limit_tokens" field.
func DailyLimitTokensLTE(v int64) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldLTE(FieldDailyLimitTokens, v))
}

// DailyLimitTokensIsNil applies the IsNil predicate on the "daily_limit_tokens" field.
func DailyLimitTokensIsNil() predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldIsNull(FieldDailyLimitTokens))
}

// DailyLimitTokensNotNil applies the NotNil predicate on the "daily_limit_tokens" field.
func DailyLimitTokensNotNil() predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.FieldNotNull(FieldDailyLimitTokens))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupCandidateTokenDailyLimitConfig) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupCandidateTokenDailyLimitConfig) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupCandidateTokenDailyLimitConfig) predicate.GroupCandidateTokenDailyLimitConfig {
	return predicate.GroupCandidateTokenDailyLimitConfig(sql.NotPredicates(p))
}
