// Code generated by ent, DO NOT EDIT.

package rbacuserversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldEQ(FieldUserID, v))
}

// AuthzVersion applies equality check predicate on the "authz_version" field. It's identical to AuthzVersionEQ.
func AuthzVersion(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldEQ(FieldAuthzVersion, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldNotIn(FieldUserID, vs...))
}

// AuthzVersionEQ applies the EQ predicate on the "authz_version" field.
func AuthzVersionEQ(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldEQ(FieldAuthzVersion, v))
}

// AuthzVersionNEQ applies the NEQ predicate on the "authz_version" field.
func AuthzVersionNEQ(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldNEQ(FieldAuthzVersion, v))
}

// AuthzVersionIn applies the In predicate on the "authz_version" field.
func AuthzVersionIn(vs ...int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldIn(FieldAuthzVersion, vs...))
}

// AuthzVersionNotIn applies the NotIn predicate on the "authz_version" field.
func AuthzVersionNotIn(vs ...int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldNotIn(FieldAuthzVersion, vs...))
}

// AuthzVersionGT applies the GT predicate on the "authz_version" field.
func AuthzVersionGT(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldGT(FieldAuthzVersion, v))
}

// AuthzVersionGTE applies the GTE predicate on the "authz_version" field.
func AuthzVersionGTE(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldGTE(FieldAuthzVersion, v))
}

// AuthzVersionLT applies the LT predicate on the "authz_version" field.
func AuthzVersionLT(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldLT(FieldAuthzVersion, v))
}

// AuthzVersionLTE applies the LTE predicate on the "authz_version" field.
func AuthzVersionLTE(v int64) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldLTE(FieldAuthzVersion, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RBACUserVersion {
	return predicate.RBACUserVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RBACUserVersion) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RBACUserVersion) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RBACUserVersion) predicate.RBACUserVersion {
	return predicate.RBACUserVersion(sql.NotPredicates(p))
}
