// Code generated by ent, DO NOT EDIT.

package tokenstataggregate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tokenstataggregate type in the database.
	Label = "token_stat_aggregate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPeriodType holds the string denoting the period_type field in the database.
	FieldPeriodType = "period_type"
	// FieldPeriodStart holds the string denoting the period_start field in the database.
	FieldPeriodStart = "period_start"
	// FieldPeriodEnd holds the string denoting the period_end field in the database.
	FieldPeriodEnd = "period_end"
	// FieldProjectionID holds the string denoting the projection_id field in the database.
	FieldProjectionID = "projection_id"
	// FieldDimensionHash holds the string denoting the dimension_hash field in the database.
	FieldDimensionHash = "dimension_hash"
	// FieldDimensionValues holds the string denoting the dimension_values field in the database.
	FieldDimensionValues = "dimension_values"
	// FieldMetricCode holds the string denoting the metric_code field in the database.
	FieldMetricCode = "metric_code"
	// FieldMetricValue holds the string denoting the metric_value field in the database.
	FieldMetricValue = "metric_value"
	// FieldSourceVersion holds the string denoting the source_version field in the database.
	FieldSourceVersion = "source_version"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldRouteAlias holds the string denoting the route_alias field in the database.
	FieldRouteAlias = "route_alias"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// Table holds the table name of the tokenstataggregate in the database.
	Table = "token_stat_aggregates"
)

// Columns holds all SQL columns for tokenstataggregate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPeriodType,
	FieldPeriodStart,
	FieldPeriodEnd,
	FieldProjectionID,
	FieldDimensionHash,
	FieldDimensionValues,
	FieldMetricCode,
	FieldMetricValue,
	FieldSourceVersion,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldRouteAlias,
	FieldAccountID,
	FieldUpstreamModel,
	FieldLastSyncedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PeriodTypeValidator is a validator for the "period_type" field. It is called by the builders before save.
	PeriodTypeValidator func(string) error
	// ProjectionIDValidator is a validator for the "projection_id" field. It is called by the builders before save.
	ProjectionIDValidator func(int64) error
	// MetricCodeValidator is a validator for the "metric_code" field. It is called by the builders before save.
	MetricCodeValidator func(string) error
	// DefaultMetricValue holds the default value on creation for the "metric_value" field.
	DefaultMetricValue int64
	// MetricValueValidator is a validator for the "metric_value" field. It is called by the builders before save.
	MetricValueValidator func(int64) error
	// DefaultSourceVersion holds the default value on creation for the "source_version" field.
	DefaultSourceVersion int64
	// SourceVersionValidator is a validator for the "source_version" field. It is called by the builders before save.
	SourceVersionValidator func(int64) error
	// RouteAliasValidator is a validator for the "route_alias" field. It is called by the builders before save.
	RouteAliasValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
)

// OrderOption defines the ordering options for the TokenStatAggregate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPeriodType orders the results by the period_type field.
func ByPeriodType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodType, opts...).ToFunc()
}

// ByPeriodStart orders the results by the period_start field.
func ByPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodStart, opts...).ToFunc()
}

// ByPeriodEnd orders the results by the period_end field.
func ByPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodEnd, opts...).ToFunc()
}

// ByProjectionID orders the results by the projection_id field.
func ByProjectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectionID, opts...).ToFunc()
}

// ByMetricCode orders the results by the metric_code field.
func ByMetricCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricCode, opts...).ToFunc()
}

// ByMetricValue orders the results by the metric_value field.
func ByMetricValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetricValue, opts...).ToFunc()
}

// BySourceVersion orders the results by the source_version field.
func BySourceVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceVersion, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByRouteAlias orders the results by the route_alias field.
func ByRouteAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteAlias, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}
