// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupcandidatetokendailyusage"
)

// GroupCandidateTokenDailyUsage is the model entity for the GroupCandidateTokenDailyUsage schema.
type GroupCandidateTokenDailyUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// RouteAlias holds the value of the "route_alias" field.
	RouteAlias string `json:"route_alias,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// UsageDate holds the value of the "usage_date" field.
	UsageDate time.Time `json:"usage_date,omitempty"`
	// UsedTokens holds the value of the "used_tokens" field.
	UsedTokens int64 `json:"used_tokens,omitempty"`
	// DailyLimitTokens holds the value of the "daily_limit_tokens" field.
	DailyLimitTokens *int64 `json:"daily_limit_tokens,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupCandidateTokenDailyUsageQuery when eager-loading is set.
	Edges        GroupCandidateTokenDailyUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupCandidateTokenDailyUsageEdges holds the relations/edges for other nodes in the graph.
type GroupCandidateTokenDailyUsageEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupCandidateTokenDailyUsageEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupCandidateTokenDailyUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupcandidatetokendailyusage.FieldID, groupcandidatetokendailyusage.FieldGroupID, groupcandidatetokendailyusage.FieldUsedTokens, groupcandidatetokendailyusage.FieldDailyLimitTokens:
			values[i] = new(sql.NullInt64)
		case groupcandidatetokendailyusage.FieldRouteAlias, groupcandidatetokendailyusage.FieldUpstreamModel:
			values[i] = new(sql.NullString)
		case groupcandidatetokendailyusage.FieldCreatedAt, groupcandidatetokendailyusage.FieldUpdatedAt, groupcandidatetokendailyusage.FieldUsageDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupCandidateTokenDailyUsage fields.
func (_m *GroupCandidateTokenDailyUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupcandidatetokendailyusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case groupcandidatetokendailyusage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case groupcandidatetokendailyusage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case groupcandidatetokendailyusage.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case groupcandidatetokendailyusage.FieldRouteAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_alias", values[i])
			} else if value.Valid {
				_m.RouteAlias = value.String
			}
		case groupcandidatetokendailyusage.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case groupcandidatetokendailyusage.FieldUsageDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field usage_date", values[i])
			} else if value.Valid {
				_m.UsageDate = value.Time
			}
		case groupcandidatetokendailyusage.FieldUsedTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used_tokens", values[i])
			} else if value.Valid {
				_m.UsedTokens = value.Int64
			}
		case groupcandidatetokendailyusage.FieldDailyLimitTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_tokens", values[i])
			} else if value.Valid {
				_m.DailyLimitTokens = new(int64)
				*_m.DailyLimitTokens = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupCandidateTokenDailyUsage.
// This includes values selected through modifiers, order, etc.
func (_m *GroupCandidateTokenDailyUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the GroupCandidateTokenDailyUsage entity.
func (_m *GroupCandidateTokenDailyUsage) QueryGroup() *GroupQuery {
	return NewGroupCandidateTokenDailyUsageClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this GroupCandidateTokenDailyUsage.
// Note that you need to call GroupCandidateTokenDailyUsage.Unwrap() before calling this method if this GroupCandidateTokenDailyUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupCandidateTokenDailyUsage) Update() *GroupCandidateTokenDailyUsageUpdateOne {
	return NewGroupCandidateTokenDailyUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupCandidateTokenDailyUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupCandidateTokenDailyUsage) Unwrap() *GroupCandidateTokenDailyUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupCandidateTokenDailyUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupCandidateTokenDailyUsage) String() string {
	var builder strings.Builder
	builder.WriteString("GroupCandidateTokenDailyUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("route_alias=")
	builder.WriteString(_m.RouteAlias)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("usage_date=")
	builder.WriteString(_m.UsageDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("used_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedTokens))
	builder.WriteString(", ")
	if v := _m.DailyLimitTokens; v != nil {
		builder.WriteString("daily_limit_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GroupCandidateTokenDailyUsages is a parsable slice of GroupCandidateTokenDailyUsage.
type GroupCandidateTokenDailyUsages []*GroupCandidateTokenDailyUsage
