// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupcandidatetokendailyusage"
)

// GroupCandidateTokenDailyUsageCreate is the builder for creating a GroupCandidateTokenDailyUsage entity.
type GroupCandidateTokenDailyUsageCreate struct {
	config
	mutation *GroupCandidateTokenDailyUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupCandidateTokenDailyUsageCreate) SetCreatedAt(v time.Time) *GroupCandidateTokenDailyUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupCandidateTokenDailyUsageCreate) SetNillableCreatedAt(v *time.Time) *GroupCandidateTokenDailyUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupCandidateTokenDailyUsageCreate) SetUpdatedAt(v time.Time) *GroupCandidateTokenDailyUsageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupCandidateTokenDailyUsageCreate) SetNillableUpdatedAt(v *time.Time) *GroupCandidateTokenDailyUsageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupCandidateTokenDailyUsageCreate) SetGroupID(v int64) *GroupCandidateTokenDailyUsageCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetRouteAlias sets the "route_alias" field.
func (_c *GroupCandidateTokenDailyUsageCreate) SetRouteAlias(v string) *GroupCandidateTokenDailyUsageCreate {
	_c.mutation.SetRouteAlias(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *GroupCandidateTokenDailyUsageCreate) SetUpstreamModel(v string) *GroupCandidateTokenDailyUsageCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetUsageDate sets the "usage_date" field.
func (_c *GroupCandidateTokenDailyUsageCreate) SetUsageDate(v time.Time) *GroupCandidateTokenDailyUsageCreate {
	_c.mutation.SetUsageDate(v)
	return _c
}

// SetUsedTokens sets the "used_tokens" field.
func (_c *GroupCandidateTokenDailyUsageCreate) SetUsedTokens(v int64) *GroupCandidateTokenDailyUsageCreate {
	_c.mutation.SetUsedTokens(v)
	return _c
}

// SetNillableUsedTokens sets the "used_tokens" field if the given value is not nil.
func (_c *GroupCandidateTokenDailyUsageCreate) SetNillableUsedTokens(v *int64) *GroupCandidateTokenDailyUsageCreate {
	if v != nil {
		_c.SetUsedTokens(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupCandidateTokenDailyUsageCreate) SetGroup(v *Group) *GroupCandidateTokenDailyUsageCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the GroupCandidateTokenDailyUsageMutation object of the builder.
func (_c *GroupCandidateTokenDailyUsageCreate) Mutation() *GroupCandidateTokenDailyUsageMutation {
	return _c.mutation
}

// Save creates the GroupCandidateTokenDailyUsage in the database.
func (_c *GroupCandidateTokenDailyUsageCreate) Save(ctx context.Context) (*GroupCandidateTokenDailyUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupCandidateTokenDailyUsageCreate) SaveX(ctx context.Context) *GroupCandidateTokenDailyUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupCandidateTokenDailyUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupCandidateTokenDailyUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupCandidateTokenDailyUsageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupcandidatetokendailyusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := groupcandidatetokendailyusage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UsedTokens(); !ok {
		v := groupcandidatetokendailyusage.DefaultUsedTokens
		_c.mutation.SetUsedTokens(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupCandidateTokenDailyUsageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyUsage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyUsage.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyUsage.group_id"`)}
	}
	if _, ok := _c.mutation.RouteAlias(); !ok {
		return &ValidationError{Name: "route_alias", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyUsage.route_alias"`)}
	}
	if v, ok := _c.mutation.RouteAlias(); ok {
		if err := groupcandidatetokendailyusage.RouteAliasValidator(v); err != nil {
			return &ValidationError{Name: "route_alias", err: fmt.Errorf(`ent: validator failed for field "GroupCandidateTokenDailyUsage.route_alias": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyUsage.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := groupcandidatetokendailyusage.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "GroupCandidateTokenDailyUsage.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsageDate(); !ok {
		return &ValidationError{Name: "usage_date", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyUsage.usage_date"`)}
	}
	if _, ok := _c.mutation.UsedTokens(); !ok {
		return &ValidationError{Name: "used_tokens", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyUsage.used_tokens"`)}
	}
	if v, ok := _c.mutation.UsedTokens(); ok {
		if err := groupcandidatetokendailyusage.UsedTokensValidator(v); err != nil {
			return &ValidationError{Name: "used_tokens", err: fmt.Errorf(`ent: validator failed for field "GroupCandidateTokenDailyUsage.used_tokens": %w`, err)}
		}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupCandidateTokenDailyUsage.group"`)}
	}
	return nil
}

func (_c *GroupCandidateTokenDailyUsageCreate) sqlSave(ctx context.Context) (*GroupCandidateTokenDailyUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupCandidateTokenDailyUsageCreate) createSpec() (*GroupCandidateTokenDailyUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupCandidateTokenDailyUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupcandidatetokendailyusage.Table, sqlgraph.NewFieldSpec(groupcandidatetokendailyusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupcandidatetokendailyusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupcandidatetokendailyusage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RouteAlias(); ok {
		_spec.SetField(groupcandidatetokendailyusage.FieldRouteAlias, field.TypeString, value)
		_node.RouteAlias = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(groupcandidatetokendailyusage.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.UsageDate(); ok {
		_spec.SetField(groupcandidatetokendailyusage.FieldUsageDate, field.TypeTime, value)
		_node.UsageDate = value
	}
	if value, ok := _c.mutation.UsedTokens(); ok {
		_spec.SetField(groupcandidatetokendailyusage.FieldUsedTokens, field.TypeInt64, value)
		_node.UsedTokens = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupcandidatetokendailyusage.GroupTable,
			Columns: []string{groupcandidatetokendailyusage.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupCandidateTokenDailyUsage.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupCandidateTokenDailyUsageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupCandidateTokenDailyUsageCreate) OnConflict(opts ...sql.ConflictOption) *GroupCandidateTokenDailyUsageUpsertOne {
	_c.conflict = opts
	return &GroupCandidateTokenDailyUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupCandidateTokenDailyUsageCreate) OnConflictColumns(columns ...string) *GroupCandidateTokenDailyUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupCandidateTokenDailyUsageUpsertOne{
		create: _c,
	}
}

type (
	// GroupCandidateTokenDailyUsageUpsertOne is the builder for "upsert"-ing
	//  one GroupCandidateTokenDailyUsage node.
	GroupCandidateTokenDailyUsageUpsertOne struct {
		create *GroupCandidateTokenDailyUsageCreate
	}

	// GroupCandidateTokenDailyUsageUpsert is the "OnConflict" setter.
	GroupCandidateTokenDailyUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupCandidateTokenDailyUsageUpsert) SetUpdatedAt(v time.Time) *GroupCandidateTokenDailyUsageUpsert {
	u.Set(groupcandidatetokendailyusage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsert) UpdateUpdatedAt() *GroupCandidateTokenDailyUsageUpsert {
	u.SetExcluded(groupcandidatetokendailyusage.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupCandidateTokenDailyUsageUpsert) SetGroupID(v int64) *GroupCandidateTokenDailyUsageUpsert {
	u.Set(groupcandidatetokendailyusage.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsert) UpdateGroupID() *GroupCandidateTokenDailyUsageUpsert {
	u.SetExcluded(groupcandidatetokendailyusage.FieldGroupID)
	return u
}

// SetRouteAlias sets the "route_alias" field.
func (u *GroupCandidateTokenDailyUsageUpsert) SetRouteAlias(v string) *GroupCandidateTokenDailyUsageUpsert {
	u.Set(groupcandidatetokendailyusage.FieldRouteAlias, v)
	return u
}

// UpdateRouteAlias sets the "route_alias" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsert) UpdateRouteAlias() *GroupCandidateTokenDailyUsageUpsert {
	u.SetExcluded(groupcandidatetokendailyusage.FieldRouteAlias)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *GroupCandidateTokenDailyUsageUpsert) SetUpstreamModel(v string) *GroupCandidateTokenDailyUsageUpsert {
	u.Set(groupcandidatetokendailyusage.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsert) UpdateUpstreamModel() *GroupCandidateTokenDailyUsageUpsert {
	u.SetExcluded(groupcandidatetokendailyusage.FieldUpstreamModel)
	return u
}

// SetUsageDate sets the "usage_date" field.
func (u *GroupCandidateTokenDailyUsageUpsert) SetUsageDate(v time.Time) *GroupCandidateTokenDailyUsageUpsert {
	u.Set(groupcandidatetokendailyusage.FieldUsageDate, v)
	return u
}

// UpdateUsageDate sets the "usage_date" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsert) UpdateUsageDate() *GroupCandidateTokenDailyUsageUpsert {
	u.SetExcluded(groupcandidatetokendailyusage.FieldUsageDate)
	return u
}

// SetUsedTokens sets the "used_tokens" field.
func (u *GroupCandidateTokenDailyUsageUpsert) SetUsedTokens(v int64) *GroupCandidateTokenDailyUsageUpsert {
	u.Set(groupcandidatetokendailyusage.FieldUsedTokens, v)
	return u
}

// UpdateUsedTokens sets the "used_tokens" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsert) UpdateUsedTokens() *GroupCandidateTokenDailyUsageUpsert {
	u.SetExcluded(groupcandidatetokendailyusage.FieldUsedTokens)
	return u
}

// AddUsedTokens adds v to the "used_tokens" field.
func (u *GroupCandidateTokenDailyUsageUpsert) AddUsedTokens(v int64) *GroupCandidateTokenDailyUsageUpsert {
	u.Add(groupcandidatetokendailyusage.FieldUsedTokens, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupCandidateTokenDailyUsageUpsertOne) UpdateNewValues() *GroupCandidateTokenDailyUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupcandidatetokendailyusage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupCandidateTokenDailyUsageUpsertOne) Ignore() *GroupCandidateTokenDailyUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupCandidateTokenDailyUsageUpsertOne) DoNothing() *GroupCandidateTokenDailyUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupCandidateTokenDailyUsageCreate.OnConflict
// documentation for more info.
func (u *GroupCandidateTokenDailyUsageUpsertOne) Update(set func(*GroupCandidateTokenDailyUsageUpsert)) *GroupCandidateTokenDailyUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupCandidateTokenDailyUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupCandidateTokenDailyUsageUpsertOne) SetUpdatedAt(v time.Time) *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertOne) UpdateUpdatedAt() *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupCandidateTokenDailyUsageUpsertOne) SetGroupID(v int64) *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertOne) UpdateGroupID() *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateGroupID()
	})
}

// SetRouteAlias sets the "route_alias" field.
func (u *GroupCandidateTokenDailyUsageUpsertOne) SetRouteAlias(v string) *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetRouteAlias(v)
	})
}

// UpdateRouteAlias sets the "route_alias" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertOne) UpdateRouteAlias() *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateRouteAlias()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *GroupCandidateTokenDailyUsageUpsertOne) SetUpstreamModel(v string) *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertOne) UpdateUpstreamModel() *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetUsageDate sets the "usage_date" field.
func (u *GroupCandidateTokenDailyUsageUpsertOne) SetUsageDate(v time.Time) *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetUsageDate(v)
	})
}

// UpdateUsageDate sets the "usage_date" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertOne) UpdateUsageDate() *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateUsageDate()
	})
}

// SetUsedTokens sets the "used_tokens" field.
func (u *GroupCandidateTokenDailyUsageUpsertOne) SetUsedTokens(v int64) *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetUsedTokens(v)
	})
}

// AddUsedTokens adds v to the "used_tokens" field.
func (u *GroupCandidateTokenDailyUsageUpsertOne) AddUsedTokens(v int64) *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.AddUsedTokens(v)
	})
}

// UpdateUsedTokens sets the "used_tokens" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertOne) UpdateUsedTokens() *GroupCandidateTokenDailyUsageUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateUsedTokens()
	})
}

// Exec executes the query.
func (u *GroupCandidateTokenDailyUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupCandidateTokenDailyUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupCandidateTokenDailyUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupCandidateTokenDailyUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupCandidateTokenDailyUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupCandidateTokenDailyUsageCreateBulk is the builder for creating many GroupCandidateTokenDailyUsage entities in bulk.
type GroupCandidateTokenDailyUsageCreateBulk struct {
	config
	err      error
	builders []*GroupCandidateTokenDailyUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupCandidateTokenDailyUsage entities in the database.
func (_c *GroupCandidateTokenDailyUsageCreateBulk) Save(ctx context.Context) ([]*GroupCandidateTokenDailyUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupCandidateTokenDailyUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupCandidateTokenDailyUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupCandidateTokenDailyUsageCreateBulk) SaveX(ctx context.Context) []*GroupCandidateTokenDailyUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupCandidateTokenDailyUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupCandidateTokenDailyUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupCandidateTokenDailyUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupCandidateTokenDailyUsageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupCandidateTokenDailyUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupCandidateTokenDailyUsageUpsertBulk {
	_c.conflict = opts
	return &GroupCandidateTokenDailyUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupCandidateTokenDailyUsageCreateBulk) OnConflictColumns(columns ...string) *GroupCandidateTokenDailyUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupCandidateTokenDailyUsageUpsertBulk{
		create: _c,
	}
}

// GroupCandidateTokenDailyUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupCandidateTokenDailyUsage nodes.
type GroupCandidateTokenDailyUsageUpsertBulk struct {
	create *GroupCandidateTokenDailyUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupCandidateTokenDailyUsageUpsertBulk) UpdateNewValues() *GroupCandidateTokenDailyUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupcandidatetokendailyusage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupCandidateTokenDailyUsageUpsertBulk) Ignore() *GroupCandidateTokenDailyUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) DoNothing() *GroupCandidateTokenDailyUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupCandidateTokenDailyUsageCreateBulk.OnConflict
// documentation for more info.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) Update(set func(*GroupCandidateTokenDailyUsageUpsert)) *GroupCandidateTokenDailyUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupCandidateTokenDailyUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) SetUpdatedAt(v time.Time) *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) UpdateUpdatedAt() *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) SetGroupID(v int64) *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) UpdateGroupID() *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateGroupID()
	})
}

// SetRouteAlias sets the "route_alias" field.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) SetRouteAlias(v string) *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetRouteAlias(v)
	})
}

// UpdateRouteAlias sets the "route_alias" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) UpdateRouteAlias() *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateRouteAlias()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) SetUpstreamModel(v string) *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) UpdateUpstreamModel() *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetUsageDate sets the "usage_date" field.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) SetUsageDate(v time.Time) *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetUsageDate(v)
	})
}

// UpdateUsageDate sets the "usage_date" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) UpdateUsageDate() *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateUsageDate()
	})
}

// SetUsedTokens sets the "used_tokens" field.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) SetUsedTokens(v int64) *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.SetUsedTokens(v)
	})
}

// AddUsedTokens adds v to the "used_tokens" field.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) AddUsedTokens(v int64) *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.AddUsedTokens(v)
	})
}

// UpdateUsedTokens sets the "used_tokens" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) UpdateUsedTokens() *GroupCandidateTokenDailyUsageUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyUsageUpsert) {
		s.UpdateUsedTokens()
	})
}

// Exec executes the query.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupCandidateTokenDailyUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupCandidateTokenDailyUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupCandidateTokenDailyUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
