// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupcandidatetokendailylimitconfig"
)

// GroupCandidateTokenDailyLimitConfigCreate is the builder for creating a GroupCandidateTokenDailyLimitConfig entity.
type GroupCandidateTokenDailyLimitConfigCreate struct {
	config
	mutation *GroupCandidateTokenDailyLimitConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetCreatedAt(v time.Time) *GroupCandidateTokenDailyLimitConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetNillableCreatedAt(v *time.Time) *GroupCandidateTokenDailyLimitConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetUpdatedAt(v time.Time) *GroupCandidateTokenDailyLimitConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetNillableUpdatedAt(v *time.Time) *GroupCandidateTokenDailyLimitConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetGroupID(v int64) *GroupCandidateTokenDailyLimitConfigCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetRouteAlias sets the "route_alias" field.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetRouteAlias(v string) *GroupCandidateTokenDailyLimitConfigCreate {
	_c.mutation.SetRouteAlias(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetUpstreamModel(v string) *GroupCandidateTokenDailyLimitConfigCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetDailyLimitTokens sets the "daily_limit_tokens" field.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetDailyLimitTokens(v int64) *GroupCandidateTokenDailyLimitConfigCreate {
	_c.mutation.SetDailyLimitTokens(v)
	return _c
}

// SetNillableDailyLimitTokens sets the "daily_limit_tokens" field if the given value is not nil.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetNillableDailyLimitTokens(v *int64) *GroupCandidateTokenDailyLimitConfigCreate {
	if v != nil {
		_c.SetDailyLimitTokens(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SetGroup(v *Group) *GroupCandidateTokenDailyLimitConfigCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the GroupCandidateTokenDailyLimitConfigMutation object of the builder.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) Mutation() *GroupCandidateTokenDailyLimitConfigMutation {
	return _c.mutation
}

// Save creates the GroupCandidateTokenDailyLimitConfig in the database.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) Save(ctx context.Context) (*GroupCandidateTokenDailyLimitConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) SaveX(ctx context.Context) *GroupCandidateTokenDailyLimitConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupcandidatetokendailylimitconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := groupcandidatetokendailylimitconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupCandidateTokenDailyLimitConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyLimitConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyLimitConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyLimitConfig.group_id"`)}
	}
	if _, ok := _c.mutation.RouteAlias(); !ok {
		return &ValidationError{Name: "route_alias", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyLimitConfig.route_alias"`)}
	}
	if v, ok := _c.mutation.RouteAlias(); ok {
		if err := groupcandidatetokendailylimitconfig.RouteAliasValidator(v); err != nil {
			return &ValidationError{Name: "route_alias", err: fmt.Errorf(`ent: validator failed for field "GroupCandidateTokenDailyLimitConfig.route_alias": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "GroupCandidateTokenDailyLimitConfig.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := groupcandidatetokendailylimitconfig.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "GroupCandidateTokenDailyLimitConfig.upstream_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DailyLimitTokens(); ok {
		if err := groupcandidatetokendailylimitconfig.DailyLimitTokensValidator(v); err != nil {
			return &ValidationError{Name: "daily_limit_tokens", err: fmt.Errorf(`ent: validator failed for field "GroupCandidateTokenDailyLimitConfig.daily_limit_tokens": %w`, err)}
		}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupCandidateTokenDailyLimitConfig.group"`)}
	}
	return nil
}

func (_c *GroupCandidateTokenDailyLimitConfigCreate) sqlSave(ctx context.Context) (*GroupCandidateTokenDailyLimitConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupCandidateTokenDailyLimitConfigCreate) createSpec() (*GroupCandidateTokenDailyLimitConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupCandidateTokenDailyLimitConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupcandidatetokendailylimitconfig.Table, sqlgraph.NewFieldSpec(groupcandidatetokendailylimitconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupcandidatetokendailylimitconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupcandidatetokendailylimitconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RouteAlias(); ok {
		_spec.SetField(groupcandidatetokendailylimitconfig.FieldRouteAlias, field.TypeString, value)
		_node.RouteAlias = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(groupcandidatetokendailylimitconfig.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.DailyLimitTokens(); ok {
		_spec.SetField(groupcandidatetokendailylimitconfig.FieldDailyLimitTokens, field.TypeInt64, value)
		_node.DailyLimitTokens = &value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupcandidatetokendailylimitconfig.GroupTable,
			Columns: []string{groupcandidatetokendailylimitconfig.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupCandidateTokenDailyLimitConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupCandidateTokenDailyLimitConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupCandidateTokenDailyLimitConfigCreate) OnConflict(opts ...sql.ConflictOption) *GroupCandidateTokenDailyLimitConfigUpsertOne {
	_c.conflict = opts
	return &GroupCandidateTokenDailyLimitConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyLimitConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupCandidateTokenDailyLimitConfigCreate) OnConflictColumns(columns ...string) *GroupCandidateTokenDailyLimitConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupCandidateTokenDailyLimitConfigUpsertOne{
		create: _c,
	}
}

type (
	// GroupCandidateTokenDailyLimitConfigUpsertOne is the builder for "upsert"-ing
	//  one GroupCandidateTokenDailyLimitConfig node.
	GroupCandidateTokenDailyLimitConfigUpsertOne struct {
		create *GroupCandidateTokenDailyLimitConfigCreate
	}

	// GroupCandidateTokenDailyLimitConfigUpsert is the "OnConflict" setter.
	GroupCandidateTokenDailyLimitConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) SetUpdatedAt(v time.Time) *GroupCandidateTokenDailyLimitConfigUpsert {
	u.Set(groupcandidatetokendailylimitconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) UpdateUpdatedAt() *GroupCandidateTokenDailyLimitConfigUpsert {
	u.SetExcluded(groupcandidatetokendailylimitconfig.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) SetGroupID(v int64) *GroupCandidateTokenDailyLimitConfigUpsert {
	u.Set(groupcandidatetokendailylimitconfig.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) UpdateGroupID() *GroupCandidateTokenDailyLimitConfigUpsert {
	u.SetExcluded(groupcandidatetokendailylimitconfig.FieldGroupID)
	return u
}

// SetRouteAlias sets the "route_alias" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) SetRouteAlias(v string) *GroupCandidateTokenDailyLimitConfigUpsert {
	u.Set(groupcandidatetokendailylimitconfig.FieldRouteAlias, v)
	return u
}

// UpdateRouteAlias sets the "route_alias" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) UpdateRouteAlias() *GroupCandidateTokenDailyLimitConfigUpsert {
	u.SetExcluded(groupcandidatetokendailylimitconfig.FieldRouteAlias)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) SetUpstreamModel(v string) *GroupCandidateTokenDailyLimitConfigUpsert {
	u.Set(groupcandidatetokendailylimitconfig.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) UpdateUpstreamModel() *GroupCandidateTokenDailyLimitConfigUpsert {
	u.SetExcluded(groupcandidatetokendailylimitconfig.FieldUpstreamModel)
	return u
}

// SetDailyLimitTokens sets the "daily_limit_tokens" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) SetDailyLimitTokens(v int64) *GroupCandidateTokenDailyLimitConfigUpsert {
	u.Set(groupcandidatetokendailylimitconfig.FieldDailyLimitTokens, v)
	return u
}

// UpdateDailyLimitTokens sets the "daily_limit_tokens" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) UpdateDailyLimitTokens() *GroupCandidateTokenDailyLimitConfigUpsert {
	u.SetExcluded(groupcandidatetokendailylimitconfig.FieldDailyLimitTokens)
	return u
}

// AddDailyLimitTokens adds v to the "daily_limit_tokens" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) AddDailyLimitTokens(v int64) *GroupCandidateTokenDailyLimitConfigUpsert {
	u.Add(groupcandidatetokendailylimitconfig.FieldDailyLimitTokens, v)
	return u
}

// ClearDailyLimitTokens clears the value of the "daily_limit_tokens" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsert) ClearDailyLimitTokens() *GroupCandidateTokenDailyLimitConfigUpsert {
	u.SetNull(groupcandidatetokendailylimitconfig.FieldDailyLimitTokens)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyLimitConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) UpdateNewValues() *GroupCandidateTokenDailyLimitConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupcandidatetokendailylimitconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyLimitConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) Ignore() *GroupCandidateTokenDailyLimitConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) DoNothing() *GroupCandidateTokenDailyLimitConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupCandidateTokenDailyLimitConfigCreate.OnConflict
// documentation for more info.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) Update(set func(*GroupCandidateTokenDailyLimitConfigUpsert)) *GroupCandidateTokenDailyLimitConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupCandidateTokenDailyLimitConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) SetUpdatedAt(v time.Time) *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) UpdateUpdatedAt() *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) SetGroupID(v int64) *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) UpdateGroupID() *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateGroupID()
	})
}

// SetRouteAlias sets the "route_alias" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) SetRouteAlias(v string) *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetRouteAlias(v)
	})
}

// UpdateRouteAlias sets the "route_alias" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) UpdateRouteAlias() *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateRouteAlias()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) SetUpstreamModel(v string) *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) UpdateUpstreamModel() *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetDailyLimitTokens sets the "daily_limit_tokens" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) SetDailyLimitTokens(v int64) *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetDailyLimitTokens(v)
	})
}

// AddDailyLimitTokens adds v to the "daily_limit_tokens" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) AddDailyLimitTokens(v int64) *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.AddDailyLimitTokens(v)
	})
}

// UpdateDailyLimitTokens sets the "daily_limit_tokens" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) UpdateDailyLimitTokens() *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateDailyLimitTokens()
	})
}

// ClearDailyLimitTokens clears the value of the "daily_limit_tokens" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) ClearDailyLimitTokens() *GroupCandidateTokenDailyLimitConfigUpsertOne {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.ClearDailyLimitTokens()
	})
}

// Exec executes the query.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupCandidateTokenDailyLimitConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupCandidateTokenDailyLimitConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupCandidateTokenDailyLimitConfigCreateBulk is the builder for creating many GroupCandidateTokenDailyLimitConfig entities in bulk.
type GroupCandidateTokenDailyLimitConfigCreateBulk struct {
	config
	err      error
	builders []*GroupCandidateTokenDailyLimitConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupCandidateTokenDailyLimitConfig entities in the database.
func (_c *GroupCandidateTokenDailyLimitConfigCreateBulk) Save(ctx context.Context) ([]*GroupCandidateTokenDailyLimitConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupCandidateTokenDailyLimitConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupCandidateTokenDailyLimitConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupCandidateTokenDailyLimitConfigCreateBulk) SaveX(ctx context.Context) []*GroupCandidateTokenDailyLimitConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupCandidateTokenDailyLimitConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupCandidateTokenDailyLimitConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupCandidateTokenDailyLimitConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupCandidateTokenDailyLimitConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupCandidateTokenDailyLimitConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	_c.conflict = opts
	return &GroupCandidateTokenDailyLimitConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyLimitConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupCandidateTokenDailyLimitConfigCreateBulk) OnConflictColumns(columns ...string) *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupCandidateTokenDailyLimitConfigUpsertBulk{
		create: _c,
	}
}

// GroupCandidateTokenDailyLimitConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupCandidateTokenDailyLimitConfig nodes.
type GroupCandidateTokenDailyLimitConfigUpsertBulk struct {
	create *GroupCandidateTokenDailyLimitConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyLimitConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) UpdateNewValues() *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupcandidatetokendailylimitconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupCandidateTokenDailyLimitConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) Ignore() *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) DoNothing() *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupCandidateTokenDailyLimitConfigCreateBulk.OnConflict
// documentation for more info.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) Update(set func(*GroupCandidateTokenDailyLimitConfigUpsert)) *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupCandidateTokenDailyLimitConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) SetUpdatedAt(v time.Time) *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) UpdateUpdatedAt() *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) SetGroupID(v int64) *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) UpdateGroupID() *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateGroupID()
	})
}

// SetRouteAlias sets the "route_alias" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) SetRouteAlias(v string) *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetRouteAlias(v)
	})
}

// UpdateRouteAlias sets the "route_alias" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) UpdateRouteAlias() *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateRouteAlias()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) SetUpstreamModel(v string) *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) UpdateUpstreamModel() *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetDailyLimitTokens sets the "daily_limit_tokens" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) SetDailyLimitTokens(v int64) *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.SetDailyLimitTokens(v)
	})
}

// AddDailyLimitTokens adds v to the "daily_limit_tokens" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) AddDailyLimitTokens(v int64) *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.AddDailyLimitTokens(v)
	})
}

// UpdateDailyLimitTokens sets the "daily_limit_tokens" field to the value that was provided on create.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) UpdateDailyLimitTokens() *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.UpdateDailyLimitTokens()
	})
}

// ClearDailyLimitTokens clears the value of the "daily_limit_tokens" field.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) ClearDailyLimitTokens() *GroupCandidateTokenDailyLimitConfigUpsertBulk {
	return u.Update(func(s *GroupCandidateTokenDailyLimitConfigUpsert) {
		s.ClearDailyLimitTokens()
	})
}

// Exec executes the query.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupCandidateTokenDailyLimitConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupCandidateTokenDailyLimitConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupCandidateTokenDailyLimitConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
