// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modeltokendailyusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelTokenDailyUsageDelete is the builder for deleting a ModelTokenDailyUsage entity.
type ModelTokenDailyUsageDelete struct {
	config
	hooks    []Hook
	mutation *ModelTokenDailyUsageMutation
}

// Where appends a list predicates to the ModelTokenDailyUsageDelete builder.
func (_d *ModelTokenDailyUsageDelete) Where(ps ...predicate.ModelTokenDailyUsage) *ModelTokenDailyUsageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelTokenDailyUsageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelTokenDailyUsageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelTokenDailyUsageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modeltokendailyusage.Table, sqlgraph.NewFieldSpec(modeltokendailyusage.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelTokenDailyUsageDeleteOne is the builder for deleting a single ModelTokenDailyUsage entity.
type ModelTokenDailyUsageDeleteOne struct {
	_d *ModelTokenDailyUsageDelete
}

// Where appends a list predicates to the ModelTokenDailyUsageDelete builder.
func (_d *ModelTokenDailyUsageDeleteOne) Where(ps ...predicate.ModelTokenDailyUsage) *ModelTokenDailyUsageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelTokenDailyUsageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modeltokendailyusage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelTokenDailyUsageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
