// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modeltokendailylimitconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelTokenDailyLimitConfigUpdate is the builder for updating ModelTokenDailyLimitConfig entities.
type ModelTokenDailyLimitConfigUpdate struct {
	config
	hooks    []Hook
	mutation *ModelTokenDailyLimitConfigMutation
}

// Where appends a list predicates to the ModelTokenDailyLimitConfigUpdate builder.
func (_u *ModelTokenDailyLimitConfigUpdate) Where(ps ...predicate.ModelTokenDailyLimitConfig) *ModelTokenDailyLimitConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelTokenDailyLimitConfigUpdate) SetUpdatedAt(v time.Time) *ModelTokenDailyLimitConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *ModelTokenDailyLimitConfigUpdate) SetModel(v string) *ModelTokenDailyLimitConfigUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ModelTokenDailyLimitConfigUpdate) SetNillableModel(v *string) *ModelTokenDailyLimitConfigUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetDailyLimitTokens sets the "daily_limit_tokens" field.
func (_u *ModelTokenDailyLimitConfigUpdate) SetDailyLimitTokens(v int64) *ModelTokenDailyLimitConfigUpdate {
	_u.mutation.ResetDailyLimitTokens()
	_u.mutation.SetDailyLimitTokens(v)
	return _u
}

// SetNillableDailyLimitTokens sets the "daily_limit_tokens" field if the given value is not nil.
func (_u *ModelTokenDailyLimitConfigUpdate) SetNillableDailyLimitTokens(v *int64) *ModelTokenDailyLimitConfigUpdate {
	if v != nil {
		_u.SetDailyLimitTokens(*v)
	}
	return _u
}

// AddDailyLimitTokens adds value to the "daily_limit_tokens" field.
func (_u *ModelTokenDailyLimitConfigUpdate) AddDailyLimitTokens(v int64) *ModelTokenDailyLimitConfigUpdate {
	_u.mutation.AddDailyLimitTokens(v)
	return _u
}

// ClearDailyLimitTokens clears the value of the "daily_limit_tokens" field.
func (_u *ModelTokenDailyLimitConfigUpdate) ClearDailyLimitTokens() *ModelTokenDailyLimitConfigUpdate {
	_u.mutation.ClearDailyLimitTokens()
	return _u
}

// Mutation returns the ModelTokenDailyLimitConfigMutation object of the builder.
func (_u *ModelTokenDailyLimitConfigUpdate) Mutation() *ModelTokenDailyLimitConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelTokenDailyLimitConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelTokenDailyLimitConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelTokenDailyLimitConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelTokenDailyLimitConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelTokenDailyLimitConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modeltokendailylimitconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelTokenDailyLimitConfigUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := modeltokendailylimitconfig.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ModelTokenDailyLimitConfig.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DailyLimitTokens(); ok {
		if err := modeltokendailylimitconfig.DailyLimitTokensValidator(v); err != nil {
			return &ValidationError{Name: "daily_limit_tokens", err: fmt.Errorf(`ent: validator failed for field "ModelTokenDailyLimitConfig.daily_limit_tokens": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelTokenDailyLimitConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modeltokendailylimitconfig.Table, modeltokendailylimitconfig.Columns, sqlgraph.NewFieldSpec(modeltokendailylimitconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modeltokendailylimitconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(modeltokendailylimitconfig.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitTokens(); ok {
		_spec.SetField(modeltokendailylimitconfig.FieldDailyLimitTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitTokens(); ok {
		_spec.AddField(modeltokendailylimitconfig.FieldDailyLimitTokens, field.TypeInt64, value)
	}
	if _u.mutation.DailyLimitTokensCleared() {
		_spec.ClearField(modeltokendailylimitconfig.FieldDailyLimitTokens, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modeltokendailylimitconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelTokenDailyLimitConfigUpdateOne is the builder for updating a single ModelTokenDailyLimitConfig entity.
type ModelTokenDailyLimitConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelTokenDailyLimitConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelTokenDailyLimitConfigUpdateOne) SetUpdatedAt(v time.Time) *ModelTokenDailyLimitConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *ModelTokenDailyLimitConfigUpdateOne) SetModel(v string) *ModelTokenDailyLimitConfigUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ModelTokenDailyLimitConfigUpdateOne) SetNillableModel(v *string) *ModelTokenDailyLimitConfigUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetDailyLimitTokens sets the "daily_limit_tokens" field.
func (_u *ModelTokenDailyLimitConfigUpdateOne) SetDailyLimitTokens(v int64) *ModelTokenDailyLimitConfigUpdateOne {
	_u.mutation.ResetDailyLimitTokens()
	_u.mutation.SetDailyLimitTokens(v)
	return _u
}

// SetNillableDailyLimitTokens sets the "daily_limit_tokens" field if the given value is not nil.
func (_u *ModelTokenDailyLimitConfigUpdateOne) SetNillableDailyLimitTokens(v *int64) *ModelTokenDailyLimitConfigUpdateOne {
	if v != nil {
		_u.SetDailyLimitTokens(*v)
	}
	return _u
}

// AddDailyLimitTokens adds value to the "daily_limit_tokens" field.
func (_u *ModelTokenDailyLimitConfigUpdateOne) AddDailyLimitTokens(v int64) *ModelTokenDailyLimitConfigUpdateOne {
	_u.mutation.AddDailyLimitTokens(v)
	return _u
}

// ClearDailyLimitTokens clears the value of the "daily_limit_tokens" field.
func (_u *ModelTokenDailyLimitConfigUpdateOne) ClearDailyLimitTokens() *ModelTokenDailyLimitConfigUpdateOne {
	_u.mutation.ClearDailyLimitTokens()
	return _u
}

// Mutation returns the ModelTokenDailyLimitConfigMutation object of the builder.
func (_u *ModelTokenDailyLimitConfigUpdateOne) Mutation() *ModelTokenDailyLimitConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelTokenDailyLimitConfigUpdate builder.
func (_u *ModelTokenDailyLimitConfigUpdateOne) Where(ps ...predicate.ModelTokenDailyLimitConfig) *ModelTokenDailyLimitConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelTokenDailyLimitConfigUpdateOne) Select(field string, fields ...string) *ModelTokenDailyLimitConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelTokenDailyLimitConfig entity.
func (_u *ModelTokenDailyLimitConfigUpdateOne) Save(ctx context.Context) (*ModelTokenDailyLimitConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelTokenDailyLimitConfigUpdateOne) SaveX(ctx context.Context) *ModelTokenDailyLimitConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelTokenDailyLimitConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelTokenDailyLimitConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelTokenDailyLimitConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modeltokendailylimitconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelTokenDailyLimitConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := modeltokendailylimitconfig.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ModelTokenDailyLimitConfig.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DailyLimitTokens(); ok {
		if err := modeltokendailylimitconfig.DailyLimitTokensValidator(v); err != nil {
			return &ValidationError{Name: "daily_limit_tokens", err: fmt.Errorf(`ent: validator failed for field "ModelTokenDailyLimitConfig.daily_limit_tokens": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelTokenDailyLimitConfigUpdateOne) sqlSave(ctx context.Context) (_node *ModelTokenDailyLimitConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modeltokendailylimitconfig.Table, modeltokendailylimitconfig.Columns, sqlgraph.NewFieldSpec(modeltokendailylimitconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelTokenDailyLimitConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modeltokendailylimitconfig.FieldID)
		for _, f := range fields {
			if !modeltokendailylimitconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modeltokendailylimitconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modeltokendailylimitconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(modeltokendailylimitconfig.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitTokens(); ok {
		_spec.SetField(modeltokendailylimitconfig.FieldDailyLimitTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitTokens(); ok {
		_spec.AddField(modeltokendailylimitconfig.FieldDailyLimitTokens, field.TypeInt64, value)
	}
	if _u.mutation.DailyLimitTokensCleared() {
		_spec.ClearField(modeltokendailylimitconfig.FieldDailyLimitTokens, field.TypeInt64)
	}
	_node = &ModelTokenDailyLimitConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modeltokendailylimitconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
