// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rbacpermission"
	"github.com/Wei-Shaw/sub2api/ent/rbacrole"
	"github.com/Wei-Shaw/sub2api/ent/rbacrolepermission"
)

// RBACRolePermissionUpdate is the builder for updating RBACRolePermission entities.
type RBACRolePermissionUpdate struct {
	config
	hooks    []Hook
	mutation *RBACRolePermissionMutation
}

// Where appends a list predicates to the RBACRolePermissionUpdate builder.
func (_u *RBACRolePermissionUpdate) Where(ps ...predicate.RBACRolePermission) *RBACRolePermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RBACRolePermissionUpdate) SetUpdatedAt(v time.Time) *RBACRolePermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *RBACRolePermissionUpdate) SetRoleID(v int64) *RBACRolePermissionUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *RBACRolePermissionUpdate) SetNillableRoleID(v *int64) *RBACRolePermissionUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *RBACRolePermissionUpdate) SetPermissionID(v int64) *RBACRolePermissionUpdate {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *RBACRolePermissionUpdate) SetNillablePermissionID(v *int64) *RBACRolePermissionUpdate {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the RBACRole entity.
func (_u *RBACRolePermissionUpdate) SetRole(v *RBACRole) *RBACRolePermissionUpdate {
	return _u.SetRoleID(v.ID)
}

// SetPermission sets the "permission" edge to the RBACPermission entity.
func (_u *RBACRolePermissionUpdate) SetPermission(v *RBACPermission) *RBACRolePermissionUpdate {
	return _u.SetPermissionID(v.ID)
}

// Mutation returns the RBACRolePermissionMutation object of the builder.
func (_u *RBACRolePermissionUpdate) Mutation() *RBACRolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the RBACRole entity.
func (_u *RBACRolePermissionUpdate) ClearRole() *RBACRolePermissionUpdate {
	_u.mutation.ClearRole()
	return _u
}

// ClearPermission clears the "permission" edge to the RBACPermission entity.
func (_u *RBACRolePermissionUpdate) ClearPermission() *RBACRolePermissionUpdate {
	_u.mutation.ClearPermission()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RBACRolePermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RBACRolePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RBACRolePermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RBACRolePermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RBACRolePermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacrolepermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RBACRolePermissionUpdate) check() error {
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RBACRolePermission.role"`)
	}
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RBACRolePermission.permission"`)
	}
	return nil
}

func (_u *RBACRolePermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacrolepermission.Table, rbacrolepermission.Columns, sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacrolepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.RoleTable,
			Columns: []string{rbacrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.RoleTable,
			Columns: []string{rbacrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.PermissionTable,
			Columns: []string{rbacrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.PermissionTable,
			Columns: []string{rbacrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RBACRolePermissionUpdateOne is the builder for updating a single RBACRolePermission entity.
type RBACRolePermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RBACRolePermissionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RBACRolePermissionUpdateOne) SetUpdatedAt(v time.Time) *RBACRolePermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *RBACRolePermissionUpdateOne) SetRoleID(v int64) *RBACRolePermissionUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *RBACRolePermissionUpdateOne) SetNillableRoleID(v *int64) *RBACRolePermissionUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *RBACRolePermissionUpdateOne) SetPermissionID(v int64) *RBACRolePermissionUpdateOne {
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *RBACRolePermissionUpdateOne) SetNillablePermissionID(v *int64) *RBACRolePermissionUpdateOne {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the RBACRole entity.
func (_u *RBACRolePermissionUpdateOne) SetRole(v *RBACRole) *RBACRolePermissionUpdateOne {
	return _u.SetRoleID(v.ID)
}

// SetPermission sets the "permission" edge to the RBACPermission entity.
func (_u *RBACRolePermissionUpdateOne) SetPermission(v *RBACPermission) *RBACRolePermissionUpdateOne {
	return _u.SetPermissionID(v.ID)
}

// Mutation returns the RBACRolePermissionMutation object of the builder.
func (_u *RBACRolePermissionUpdateOne) Mutation() *RBACRolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the RBACRole entity.
func (_u *RBACRolePermissionUpdateOne) ClearRole() *RBACRolePermissionUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// ClearPermission clears the "permission" edge to the RBACPermission entity.
func (_u *RBACRolePermissionUpdateOne) ClearPermission() *RBACRolePermissionUpdateOne {
	_u.mutation.ClearPermission()
	return _u
}

// Where appends a list predicates to the RBACRolePermissionUpdate builder.
func (_u *RBACRolePermissionUpdateOne) Where(ps ...predicate.RBACRolePermission) *RBACRolePermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RBACRolePermissionUpdateOne) Select(field string, fields ...string) *RBACRolePermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RBACRolePermission entity.
func (_u *RBACRolePermissionUpdateOne) Save(ctx context.Context) (*RBACRolePermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RBACRolePermissionUpdateOne) SaveX(ctx context.Context) *RBACRolePermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RBACRolePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RBACRolePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RBACRolePermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rbacrolepermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RBACRolePermissionUpdateOne) check() error {
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RBACRolePermission.role"`)
	}
	if _u.mutation.PermissionCleared() && len(_u.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RBACRolePermission.permission"`)
	}
	return nil
}

func (_u *RBACRolePermissionUpdateOne) sqlSave(ctx context.Context) (_node *RBACRolePermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacrolepermission.Table, rbacrolepermission.Columns, sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RBACRolePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacrolepermission.FieldID)
		for _, f := range fields {
			if !rbacrolepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacrolepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacrolepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.RoleTable,
			Columns: []string{rbacrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.RoleTable,
			Columns: []string{rbacrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.PermissionTable,
			Columns: []string{rbacrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacrolepermission.PermissionTable,
			Columns: []string{rbacrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RBACRolePermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
