// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rbacpolicystate"
)

// RBACPolicyStateDelete is the builder for deleting a RBACPolicyState entity.
type RBACPolicyStateDelete struct {
	config
	hooks    []Hook
	mutation *RBACPolicyStateMutation
}

// Where appends a list predicates to the RBACPolicyStateDelete builder.
func (_d *RBACPolicyStateDelete) Where(ps ...predicate.RBACPolicyState) *RBACPolicyStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RBACPolicyStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RBACPolicyStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RBACPolicyStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rbacpolicystate.Table, sqlgraph.NewFieldSpec(rbacpolicystate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RBACPolicyStateDeleteOne is the builder for deleting a single RBACPolicyState entity.
type RBACPolicyStateDeleteOne struct {
	_d *RBACPolicyStateDelete
}

// Where appends a list predicates to the RBACPolicyStateDelete builder.
func (_d *RBACPolicyStateDeleteOne) Where(ps ...predicate.RBACPolicyState) *RBACPolicyStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RBACPolicyStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rbacpolicystate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RBACPolicyStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
