// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rbacrole"
	"github.com/Wei-Shaw/sub2api/ent/rbacrolepermission"
	"github.com/Wei-Shaw/sub2api/ent/rbacuserrole"
)

// RBACRoleUpdate is the builder for updating RBACRole entities.
type RBACRoleUpdate struct {
	config
	hooks    []Hook
	mutation *RBACRoleMutation
}

// Where appends a list predicates to the RBACRoleUpdate builder.
func (_u *RBACRoleUpdate) Where(ps ...predicate.RBACRole) *RBACRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RBACRoleUpdate) SetUpdatedAt(v time.Time) *RBACRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RBACRoleUpdate) SetDeletedAt(v time.Time) *RBACRoleUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RBACRoleUpdate) SetNillableDeletedAt(v *time.Time) *RBACRoleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RBACRoleUpdate) ClearDeletedAt() *RBACRoleUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *RBACRoleUpdate) SetCode(v string) *RBACRoleUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RBACRoleUpdate) SetNillableCode(v *string) *RBACRoleUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RBACRoleUpdate) SetName(v string) *RBACRoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RBACRoleUpdate) SetNillableName(v *string) *RBACRoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RBACRoleUpdate) SetDescription(v string) *RBACRoleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RBACRoleUpdate) SetNillableDescription(v *string) *RBACRoleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *RBACRoleUpdate) SetIsSystem(v bool) *RBACRoleUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *RBACRoleUpdate) SetNillableIsSystem(v *bool) *RBACRoleUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RBACRoleUpdate) SetStatus(v string) *RBACRoleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RBACRoleUpdate) SetNillableStatus(v *string) *RBACRoleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddUserRoleIDs adds the "user_roles" edge to the RBACUserRole entity by IDs.
func (_u *RBACRoleUpdate) AddUserRoleIDs(ids ...int64) *RBACRoleUpdate {
	_u.mutation.AddUserRoleIDs(ids...)
	return _u
}

// AddUserRoles adds the "user_roles" edges to the RBACUserRole entity.
func (_u *RBACRoleUpdate) AddUserRoles(v ...*RBACUserRole) *RBACRoleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserRoleIDs(ids...)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RBACRolePermission entity by IDs.
func (_u *RBACRoleUpdate) AddRolePermissionIDs(ids ...int64) *RBACRoleUpdate {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RBACRolePermission entity.
func (_u *RBACRoleUpdate) AddRolePermissions(v ...*RBACRolePermission) *RBACRoleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// Mutation returns the RBACRoleMutation object of the builder.
func (_u *RBACRoleUpdate) Mutation() *RBACRoleMutation {
	return _u.mutation
}

// ClearUserRoles clears all "user_roles" edges to the RBACUserRole entity.
func (_u *RBACRoleUpdate) ClearUserRoles() *RBACRoleUpdate {
	_u.mutation.ClearUserRoles()
	return _u
}

// RemoveUserRoleIDs removes the "user_roles" edge to RBACUserRole entities by IDs.
func (_u *RBACRoleUpdate) RemoveUserRoleIDs(ids ...int64) *RBACRoleUpdate {
	_u.mutation.RemoveUserRoleIDs(ids...)
	return _u
}

// RemoveUserRoles removes "user_roles" edges to RBACUserRole entities.
func (_u *RBACRoleUpdate) RemoveUserRoles(v ...*RBACUserRole) *RBACRoleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserRoleIDs(ids...)
}

// ClearRolePermissions clears all "role_permissions" edges to the RBACRolePermission entity.
func (_u *RBACRoleUpdate) ClearRolePermissions() *RBACRoleUpdate {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RBACRolePermission entities by IDs.
func (_u *RBACRoleUpdate) RemoveRolePermissionIDs(ids ...int64) *RBACRoleUpdate {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RBACRolePermission entities.
func (_u *RBACRoleUpdate) RemoveRolePermissions(v ...*RBACRolePermission) *RBACRoleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RBACRoleUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RBACRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RBACRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RBACRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RBACRoleUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if rbacrole.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized rbacrole.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := rbacrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RBACRoleUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := rbacrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RBACRole.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := rbacrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RBACRole.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := rbacrole.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RBACRole.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rbacrole.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RBACRole.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RBACRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacrole.Table, rbacrole.Columns, sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(rbacrole.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(rbacrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(rbacrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rbacrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rbacrole.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(rbacrole.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rbacrole.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !_u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RBACRoleUpdateOne is the builder for updating a single RBACRole entity.
type RBACRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RBACRoleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RBACRoleUpdateOne) SetUpdatedAt(v time.Time) *RBACRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RBACRoleUpdateOne) SetDeletedAt(v time.Time) *RBACRoleUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RBACRoleUpdateOne) SetNillableDeletedAt(v *time.Time) *RBACRoleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RBACRoleUpdateOne) ClearDeletedAt() *RBACRoleUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *RBACRoleUpdateOne) SetCode(v string) *RBACRoleUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RBACRoleUpdateOne) SetNillableCode(v *string) *RBACRoleUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RBACRoleUpdateOne) SetName(v string) *RBACRoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RBACRoleUpdateOne) SetNillableName(v *string) *RBACRoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RBACRoleUpdateOne) SetDescription(v string) *RBACRoleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RBACRoleUpdateOne) SetNillableDescription(v *string) *RBACRoleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *RBACRoleUpdateOne) SetIsSystem(v bool) *RBACRoleUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *RBACRoleUpdateOne) SetNillableIsSystem(v *bool) *RBACRoleUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RBACRoleUpdateOne) SetStatus(v string) *RBACRoleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RBACRoleUpdateOne) SetNillableStatus(v *string) *RBACRoleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddUserRoleIDs adds the "user_roles" edge to the RBACUserRole entity by IDs.
func (_u *RBACRoleUpdateOne) AddUserRoleIDs(ids ...int64) *RBACRoleUpdateOne {
	_u.mutation.AddUserRoleIDs(ids...)
	return _u
}

// AddUserRoles adds the "user_roles" edges to the RBACUserRole entity.
func (_u *RBACRoleUpdateOne) AddUserRoles(v ...*RBACUserRole) *RBACRoleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserRoleIDs(ids...)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RBACRolePermission entity by IDs.
func (_u *RBACRoleUpdateOne) AddRolePermissionIDs(ids ...int64) *RBACRoleUpdateOne {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RBACRolePermission entity.
func (_u *RBACRoleUpdateOne) AddRolePermissions(v ...*RBACRolePermission) *RBACRoleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// Mutation returns the RBACRoleMutation object of the builder.
func (_u *RBACRoleUpdateOne) Mutation() *RBACRoleMutation {
	return _u.mutation
}

// ClearUserRoles clears all "user_roles" edges to the RBACUserRole entity.
func (_u *RBACRoleUpdateOne) ClearUserRoles() *RBACRoleUpdateOne {
	_u.mutation.ClearUserRoles()
	return _u
}

// RemoveUserRoleIDs removes the "user_roles" edge to RBACUserRole entities by IDs.
func (_u *RBACRoleUpdateOne) RemoveUserRoleIDs(ids ...int64) *RBACRoleUpdateOne {
	_u.mutation.RemoveUserRoleIDs(ids...)
	return _u
}

// RemoveUserRoles removes "user_roles" edges to RBACUserRole entities.
func (_u *RBACRoleUpdateOne) RemoveUserRoles(v ...*RBACUserRole) *RBACRoleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserRoleIDs(ids...)
}

// ClearRolePermissions clears all "role_permissions" edges to the RBACRolePermission entity.
func (_u *RBACRoleUpdateOne) ClearRolePermissions() *RBACRoleUpdateOne {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RBACRolePermission entities by IDs.
func (_u *RBACRoleUpdateOne) RemoveRolePermissionIDs(ids ...int64) *RBACRoleUpdateOne {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RBACRolePermission entities.
func (_u *RBACRoleUpdateOne) RemoveRolePermissions(v ...*RBACRolePermission) *RBACRoleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// Where appends a list predicates to the RBACRoleUpdate builder.
func (_u *RBACRoleUpdateOne) Where(ps ...predicate.RBACRole) *RBACRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RBACRoleUpdateOne) Select(field string, fields ...string) *RBACRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RBACRole entity.
func (_u *RBACRoleUpdateOne) Save(ctx context.Context) (*RBACRole, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RBACRoleUpdateOne) SaveX(ctx context.Context) *RBACRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RBACRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RBACRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RBACRoleUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if rbacrole.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized rbacrole.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := rbacrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RBACRoleUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := rbacrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "RBACRole.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := rbacrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RBACRole.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := rbacrole.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RBACRole.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rbacrole.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RBACRole.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RBACRoleUpdateOne) sqlSave(ctx context.Context) (_node *RBACRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacrole.Table, rbacrole.Columns, sqlgraph.NewFieldSpec(rbacrole.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RBACRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacrole.FieldID)
		for _, f := range fields {
			if !rbacrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(rbacrole.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(rbacrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(rbacrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rbacrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rbacrole.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(rbacrole.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rbacrole.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !_u.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.UserRolesTable,
			Columns: []string{rbacrole.UserRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacuserrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rbacrole.RolePermissionsTable,
			Columns: []string{rbacrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacrolepermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RBACRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
