// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rbacauditlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RBACAuditLogUpdate is the builder for updating RBACAuditLog entities.
type RBACAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *RBACAuditLogMutation
}

// Where appends a list predicates to the RBACAuditLogUpdate builder.
func (_u *RBACAuditLogUpdate) Where(ps ...predicate.RBACAuditLog) *RBACAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *RBACAuditLogUpdate) SetActorUserID(v int64) *RBACAuditLogUpdate {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *RBACAuditLogUpdate) SetNillableActorUserID(v *int64) *RBACAuditLogUpdate {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *RBACAuditLogUpdate) ClearActorUserID() *RBACAuditLogUpdate {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetAction sets the "action" field.
func (_u *RBACAuditLogUpdate) SetAction(v string) *RBACAuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RBACAuditLogUpdate) SetNillableAction(v *string) *RBACAuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *RBACAuditLogUpdate) SetTargetType(v string) *RBACAuditLogUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *RBACAuditLogUpdate) SetNillableTargetType(v *string) *RBACAuditLogUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *RBACAuditLogUpdate) SetTargetID(v string) *RBACAuditLogUpdate {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *RBACAuditLogUpdate) SetNillableTargetID(v *string) *RBACAuditLogUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetBeforeData sets the "before_data" field.
func (_u *RBACAuditLogUpdate) SetBeforeData(v map[string]interface{}) *RBACAuditLogUpdate {
	_u.mutation.SetBeforeData(v)
	return _u
}

// ClearBeforeData clears the value of the "before_data" field.
func (_u *RBACAuditLogUpdate) ClearBeforeData() *RBACAuditLogUpdate {
	_u.mutation.ClearBeforeData()
	return _u
}

// SetAfterData sets the "after_data" field.
func (_u *RBACAuditLogUpdate) SetAfterData(v map[string]interface{}) *RBACAuditLogUpdate {
	_u.mutation.SetAfterData(v)
	return _u
}

// ClearAfterData clears the value of the "after_data" field.
func (_u *RBACAuditLogUpdate) ClearAfterData() *RBACAuditLogUpdate {
	_u.mutation.ClearAfterData()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RBACAuditLogUpdate) SetRequestID(v string) *RBACAuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RBACAuditLogUpdate) SetNillableRequestID(v *string) *RBACAuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RBACAuditLogUpdate) SetIPAddress(v string) *RBACAuditLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RBACAuditLogUpdate) SetNillableIPAddress(v *string) *RBACAuditLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetActorID sets the "actor" edge to the User entity by ID.
func (_u *RBACAuditLogUpdate) SetActorID(id int64) *RBACAuditLogUpdate {
	_u.mutation.SetActorID(id)
	return _u
}

// SetNillableActorID sets the "actor" edge to the User entity by ID if the given value is not nil.
func (_u *RBACAuditLogUpdate) SetNillableActorID(id *int64) *RBACAuditLogUpdate {
	if id != nil {
		_u = _u.SetActorID(*id)
	}
	return _u
}

// SetActor sets the "actor" edge to the User entity.
func (_u *RBACAuditLogUpdate) SetActor(v *User) *RBACAuditLogUpdate {
	return _u.SetActorID(v.ID)
}

// Mutation returns the RBACAuditLogMutation object of the builder.
func (_u *RBACAuditLogUpdate) Mutation() *RBACAuditLogMutation {
	return _u.mutation
}

// ClearActor clears the "actor" edge to the User entity.
func (_u *RBACAuditLogUpdate) ClearActor() *RBACAuditLogUpdate {
	_u.mutation.ClearActor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RBACAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RBACAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RBACAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RBACAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RBACAuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := rbacauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := rbacauditlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := rbacauditlog.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.target_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := rbacauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := rbacauditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.ip_address": %w`, err)}
		}
	}
	return nil
}

func (_u *RBACAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacauditlog.Table, rbacauditlog.Columns, sqlgraph.NewFieldSpec(rbacauditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(rbacauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(rbacauditlog.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(rbacauditlog.FieldTargetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BeforeData(); ok {
		_spec.SetField(rbacauditlog.FieldBeforeData, field.TypeJSON, value)
	}
	if _u.mutation.BeforeDataCleared() {
		_spec.ClearField(rbacauditlog.FieldBeforeData, field.TypeJSON)
	}
	if value, ok := _u.mutation.AfterData(); ok {
		_spec.SetField(rbacauditlog.FieldAfterData, field.TypeJSON, value)
	}
	if _u.mutation.AfterDataCleared() {
		_spec.ClearField(rbacauditlog.FieldAfterData, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(rbacauditlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(rbacauditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacauditlog.ActorTable,
			Columns: []string{rbacauditlog.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacauditlog.ActorTable,
			Columns: []string{rbacauditlog.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RBACAuditLogUpdateOne is the builder for updating a single RBACAuditLog entity.
type RBACAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RBACAuditLogMutation
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *RBACAuditLogUpdateOne) SetActorUserID(v int64) *RBACAuditLogUpdateOne {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *RBACAuditLogUpdateOne) SetNillableActorUserID(v *int64) *RBACAuditLogUpdateOne {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *RBACAuditLogUpdateOne) ClearActorUserID() *RBACAuditLogUpdateOne {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetAction sets the "action" field.
func (_u *RBACAuditLogUpdateOne) SetAction(v string) *RBACAuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RBACAuditLogUpdateOne) SetNillableAction(v *string) *RBACAuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *RBACAuditLogUpdateOne) SetTargetType(v string) *RBACAuditLogUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *RBACAuditLogUpdateOne) SetNillableTargetType(v *string) *RBACAuditLogUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *RBACAuditLogUpdateOne) SetTargetID(v string) *RBACAuditLogUpdateOne {
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *RBACAuditLogUpdateOne) SetNillableTargetID(v *string) *RBACAuditLogUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// SetBeforeData sets the "before_data" field.
func (_u *RBACAuditLogUpdateOne) SetBeforeData(v map[string]interface{}) *RBACAuditLogUpdateOne {
	_u.mutation.SetBeforeData(v)
	return _u
}

// ClearBeforeData clears the value of the "before_data" field.
func (_u *RBACAuditLogUpdateOne) ClearBeforeData() *RBACAuditLogUpdateOne {
	_u.mutation.ClearBeforeData()
	return _u
}

// SetAfterData sets the "after_data" field.
func (_u *RBACAuditLogUpdateOne) SetAfterData(v map[string]interface{}) *RBACAuditLogUpdateOne {
	_u.mutation.SetAfterData(v)
	return _u
}

// ClearAfterData clears the value of the "after_data" field.
func (_u *RBACAuditLogUpdateOne) ClearAfterData() *RBACAuditLogUpdateOne {
	_u.mutation.ClearAfterData()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RBACAuditLogUpdateOne) SetRequestID(v string) *RBACAuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RBACAuditLogUpdateOne) SetNillableRequestID(v *string) *RBACAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RBACAuditLogUpdateOne) SetIPAddress(v string) *RBACAuditLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RBACAuditLogUpdateOne) SetNillableIPAddress(v *string) *RBACAuditLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// SetActorID sets the "actor" edge to the User entity by ID.
func (_u *RBACAuditLogUpdateOne) SetActorID(id int64) *RBACAuditLogUpdateOne {
	_u.mutation.SetActorID(id)
	return _u
}

// SetNillableActorID sets the "actor" edge to the User entity by ID if the given value is not nil.
func (_u *RBACAuditLogUpdateOne) SetNillableActorID(id *int64) *RBACAuditLogUpdateOne {
	if id != nil {
		_u = _u.SetActorID(*id)
	}
	return _u
}

// SetActor sets the "actor" edge to the User entity.
func (_u *RBACAuditLogUpdateOne) SetActor(v *User) *RBACAuditLogUpdateOne {
	return _u.SetActorID(v.ID)
}

// Mutation returns the RBACAuditLogMutation object of the builder.
func (_u *RBACAuditLogUpdateOne) Mutation() *RBACAuditLogMutation {
	return _u.mutation
}

// ClearActor clears the "actor" edge to the User entity.
func (_u *RBACAuditLogUpdateOne) ClearActor() *RBACAuditLogUpdateOne {
	_u.mutation.ClearActor()
	return _u
}

// Where appends a list predicates to the RBACAuditLogUpdate builder.
func (_u *RBACAuditLogUpdateOne) Where(ps ...predicate.RBACAuditLog) *RBACAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RBACAuditLogUpdateOne) Select(field string, fields ...string) *RBACAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RBACAuditLog entity.
func (_u *RBACAuditLogUpdateOne) Save(ctx context.Context) (*RBACAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RBACAuditLogUpdateOne) SaveX(ctx context.Context) *RBACAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RBACAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RBACAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RBACAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := rbacauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := rbacauditlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.target_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetID(); ok {
		if err := rbacauditlog.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.target_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := rbacauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := rbacauditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "RBACAuditLog.ip_address": %w`, err)}
		}
	}
	return nil
}

func (_u *RBACAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *RBACAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacauditlog.Table, rbacauditlog.Columns, sqlgraph.NewFieldSpec(rbacauditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RBACAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacauditlog.FieldID)
		for _, f := range fields {
			if !rbacauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(rbacauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(rbacauditlog.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(rbacauditlog.FieldTargetID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BeforeData(); ok {
		_spec.SetField(rbacauditlog.FieldBeforeData, field.TypeJSON, value)
	}
	if _u.mutation.BeforeDataCleared() {
		_spec.ClearField(rbacauditlog.FieldBeforeData, field.TypeJSON)
	}
	if value, ok := _u.mutation.AfterData(); ok {
		_spec.SetField(rbacauditlog.FieldAfterData, field.TypeJSON, value)
	}
	if _u.mutation.AfterDataCleared() {
		_spec.ClearField(rbacauditlog.FieldAfterData, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(rbacauditlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(rbacauditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacauditlog.ActorTable,
			Columns: []string{rbacauditlog.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rbacauditlog.ActorTable,
			Columns: []string{rbacauditlog.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RBACAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
