// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/rbacpolicystate"
)

// RBACPolicyStateCreate is the builder for creating a RBACPolicyState entity.
type RBACPolicyStateCreate struct {
	config
	mutation *RBACPolicyStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPolicyVersion sets the "policy_version" field.
func (_c *RBACPolicyStateCreate) SetPolicyVersion(v int64) *RBACPolicyStateCreate {
	_c.mutation.SetPolicyVersion(v)
	return _c
}

// SetNillablePolicyVersion sets the "policy_version" field if the given value is not nil.
func (_c *RBACPolicyStateCreate) SetNillablePolicyVersion(v *int64) *RBACPolicyStateCreate {
	if v != nil {
		_c.SetPolicyVersion(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RBACPolicyStateCreate) SetUpdatedAt(v time.Time) *RBACPolicyStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RBACPolicyStateCreate) SetNillableUpdatedAt(v *time.Time) *RBACPolicyStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the RBACPolicyStateMutation object of the builder.
func (_c *RBACPolicyStateCreate) Mutation() *RBACPolicyStateMutation {
	return _c.mutation
}

// Save creates the RBACPolicyState in the database.
func (_c *RBACPolicyStateCreate) Save(ctx context.Context) (*RBACPolicyState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RBACPolicyStateCreate) SaveX(ctx context.Context) *RBACPolicyState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RBACPolicyStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RBACPolicyStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RBACPolicyStateCreate) defaults() {
	if _, ok := _c.mutation.PolicyVersion(); !ok {
		v := rbacpolicystate.DefaultPolicyVersion
		_c.mutation.SetPolicyVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rbacpolicystate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RBACPolicyStateCreate) check() error {
	if _, ok := _c.mutation.PolicyVersion(); !ok {
		return &ValidationError{Name: "policy_version", err: errors.New(`ent: missing required field "RBACPolicyState.policy_version"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RBACPolicyState.updated_at"`)}
	}
	return nil
}

func (_c *RBACPolicyStateCreate) sqlSave(ctx context.Context) (*RBACPolicyState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RBACPolicyStateCreate) createSpec() (*RBACPolicyState, *sqlgraph.CreateSpec) {
	var (
		_node = &RBACPolicyState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rbacpolicystate.Table, sqlgraph.NewFieldSpec(rbacpolicystate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PolicyVersion(); ok {
		_spec.SetField(rbacpolicystate.FieldPolicyVersion, field.TypeInt64, value)
		_node.PolicyVersion = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rbacpolicystate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RBACPolicyState.Create().
//		SetPolicyVersion(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RBACPolicyStateUpsert) {
//			SetPolicyVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *RBACPolicyStateCreate) OnConflict(opts ...sql.ConflictOption) *RBACPolicyStateUpsertOne {
	_c.conflict = opts
	return &RBACPolicyStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RBACPolicyState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RBACPolicyStateCreate) OnConflictColumns(columns ...string) *RBACPolicyStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RBACPolicyStateUpsertOne{
		create: _c,
	}
}

type (
	// RBACPolicyStateUpsertOne is the builder for "upsert"-ing
	//  one RBACPolicyState node.
	RBACPolicyStateUpsertOne struct {
		create *RBACPolicyStateCreate
	}

	// RBACPolicyStateUpsert is the "OnConflict" setter.
	RBACPolicyStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetPolicyVersion sets the "policy_version" field.
func (u *RBACPolicyStateUpsert) SetPolicyVersion(v int64) *RBACPolicyStateUpsert {
	u.Set(rbacpolicystate.FieldPolicyVersion, v)
	return u
}

// UpdatePolicyVersion sets the "policy_version" field to the value that was provided on create.
func (u *RBACPolicyStateUpsert) UpdatePolicyVersion() *RBACPolicyStateUpsert {
	u.SetExcluded(rbacpolicystate.FieldPolicyVersion)
	return u
}

// AddPolicyVersion adds v to the "policy_version" field.
func (u *RBACPolicyStateUpsert) AddPolicyVersion(v int64) *RBACPolicyStateUpsert {
	u.Add(rbacpolicystate.FieldPolicyVersion, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RBACPolicyStateUpsert) SetUpdatedAt(v time.Time) *RBACPolicyStateUpsert {
	u.Set(rbacpolicystate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RBACPolicyStateUpsert) UpdateUpdatedAt() *RBACPolicyStateUpsert {
	u.SetExcluded(rbacpolicystate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RBACPolicyState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RBACPolicyStateUpsertOne) UpdateNewValues() *RBACPolicyStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RBACPolicyState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RBACPolicyStateUpsertOne) Ignore() *RBACPolicyStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RBACPolicyStateUpsertOne) DoNothing() *RBACPolicyStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RBACPolicyStateCreate.OnConflict
// documentation for more info.
func (u *RBACPolicyStateUpsertOne) Update(set func(*RBACPolicyStateUpsert)) *RBACPolicyStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RBACPolicyStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetPolicyVersion sets the "policy_version" field.
func (u *RBACPolicyStateUpsertOne) SetPolicyVersion(v int64) *RBACPolicyStateUpsertOne {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.SetPolicyVersion(v)
	})
}

// AddPolicyVersion adds v to the "policy_version" field.
func (u *RBACPolicyStateUpsertOne) AddPolicyVersion(v int64) *RBACPolicyStateUpsertOne {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.AddPolicyVersion(v)
	})
}

// UpdatePolicyVersion sets the "policy_version" field to the value that was provided on create.
func (u *RBACPolicyStateUpsertOne) UpdatePolicyVersion() *RBACPolicyStateUpsertOne {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.UpdatePolicyVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RBACPolicyStateUpsertOne) SetUpdatedAt(v time.Time) *RBACPolicyStateUpsertOne {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RBACPolicyStateUpsertOne) UpdateUpdatedAt() *RBACPolicyStateUpsertOne {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RBACPolicyStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RBACPolicyStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RBACPolicyStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RBACPolicyStateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RBACPolicyStateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RBACPolicyStateCreateBulk is the builder for creating many RBACPolicyState entities in bulk.
type RBACPolicyStateCreateBulk struct {
	config
	err      error
	builders []*RBACPolicyStateCreate
	conflict []sql.ConflictOption
}

// Save creates the RBACPolicyState entities in the database.
func (_c *RBACPolicyStateCreateBulk) Save(ctx context.Context) ([]*RBACPolicyState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RBACPolicyState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RBACPolicyStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RBACPolicyStateCreateBulk) SaveX(ctx context.Context) []*RBACPolicyState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RBACPolicyStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RBACPolicyStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RBACPolicyState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RBACPolicyStateUpsert) {
//			SetPolicyVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *RBACPolicyStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *RBACPolicyStateUpsertBulk {
	_c.conflict = opts
	return &RBACPolicyStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RBACPolicyState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RBACPolicyStateCreateBulk) OnConflictColumns(columns ...string) *RBACPolicyStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RBACPolicyStateUpsertBulk{
		create: _c,
	}
}

// RBACPolicyStateUpsertBulk is the builder for "upsert"-ing
// a bulk of RBACPolicyState nodes.
type RBACPolicyStateUpsertBulk struct {
	create *RBACPolicyStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RBACPolicyState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RBACPolicyStateUpsertBulk) UpdateNewValues() *RBACPolicyStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RBACPolicyState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RBACPolicyStateUpsertBulk) Ignore() *RBACPolicyStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RBACPolicyStateUpsertBulk) DoNothing() *RBACPolicyStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RBACPolicyStateCreateBulk.OnConflict
// documentation for more info.
func (u *RBACPolicyStateUpsertBulk) Update(set func(*RBACPolicyStateUpsert)) *RBACPolicyStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RBACPolicyStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetPolicyVersion sets the "policy_version" field.
func (u *RBACPolicyStateUpsertBulk) SetPolicyVersion(v int64) *RBACPolicyStateUpsertBulk {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.SetPolicyVersion(v)
	})
}

// AddPolicyVersion adds v to the "policy_version" field.
func (u *RBACPolicyStateUpsertBulk) AddPolicyVersion(v int64) *RBACPolicyStateUpsertBulk {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.AddPolicyVersion(v)
	})
}

// UpdatePolicyVersion sets the "policy_version" field to the value that was provided on create.
func (u *RBACPolicyStateUpsertBulk) UpdatePolicyVersion() *RBACPolicyStateUpsertBulk {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.UpdatePolicyVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RBACPolicyStateUpsertBulk) SetUpdatedAt(v time.Time) *RBACPolicyStateUpsertBulk {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RBACPolicyStateUpsertBulk) UpdateUpdatedAt() *RBACPolicyStateUpsertBulk {
	return u.Update(func(s *RBACPolicyStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RBACPolicyStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RBACPolicyStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RBACPolicyStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RBACPolicyStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
