// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/rbacrole"
	"github.com/Wei-Shaw/sub2api/ent/rbacuserrole"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RBACUserRole is the model entity for the RBACUserRole schema.
type RBACUserRole struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID int64 `json:"role_id,omitempty"`
	// AssignedBy holds the value of the "assigned_by" field.
	AssignedBy *int64 `json:"assigned_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RBACUserRoleQuery when eager-loading is set.
	Edges        RBACUserRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RBACUserRoleEdges holds the relations/edges for other nodes in the graph.
type RBACUserRoleEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Role holds the value of the role edge.
	Role *RBACRole `json:"role,omitempty"`
	// Assigner holds the value of the assigner edge.
	Assigner *User `json:"assigner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RBACUserRoleEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RBACUserRoleEdges) RoleOrErr() (*RBACRole, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: rbacrole.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// AssignerOrErr returns the Assigner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RBACUserRoleEdges) AssignerOrErr() (*User, error) {
	if e.Assigner != nil {
		return e.Assigner, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assigner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RBACUserRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rbacuserrole.FieldID, rbacuserrole.FieldUserID, rbacuserrole.FieldRoleID, rbacuserrole.FieldAssignedBy:
			values[i] = new(sql.NullInt64)
		case rbacuserrole.FieldCreatedAt, rbacuserrole.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RBACUserRole fields.
func (_m *RBACUserRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rbacuserrole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rbacuserrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rbacuserrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case rbacuserrole.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case rbacuserrole.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = value.Int64
			}
		case rbacuserrole.FieldAssignedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_by", values[i])
			} else if value.Valid {
				_m.AssignedBy = new(int64)
				*_m.AssignedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RBACUserRole.
// This includes values selected through modifiers, order, etc.
func (_m *RBACUserRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the RBACUserRole entity.
func (_m *RBACUserRole) QueryUser() *UserQuery {
	return NewRBACUserRoleClient(_m.config).QueryUser(_m)
}

// QueryRole queries the "role" edge of the RBACUserRole entity.
func (_m *RBACUserRole) QueryRole() *RBACRoleQuery {
	return NewRBACUserRoleClient(_m.config).QueryRole(_m)
}

// QueryAssigner queries the "assigner" edge of the RBACUserRole entity.
func (_m *RBACUserRole) QueryAssigner() *UserQuery {
	return NewRBACUserRoleClient(_m.config).QueryAssigner(_m)
}

// Update returns a builder for updating this RBACUserRole.
// Note that you need to call RBACUserRole.Unwrap() before calling this method if this RBACUserRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RBACUserRole) Update() *RBACUserRoleUpdateOne {
	return NewRBACUserRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RBACUserRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RBACUserRole) Unwrap() *RBACUserRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RBACUserRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RBACUserRole) String() string {
	var builder strings.Builder
	builder.WriteString("RBACUserRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	if v := _m.AssignedBy; v != nil {
		builder.WriteString("assigned_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RBACUserRoles is a parsable slice of RBACUserRole.
type RBACUserRoles []*RBACUserRole
