// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/tokenstatprojection"
)

// TokenStatProjection is the model entity for the TokenStatProjection schema.
type TokenStatProjection struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DimensionCodes holds the value of the "dimension_codes" field.
	DimensionCodes []string `json:"dimension_codes,omitempty"`
	// DimensionSignature holds the value of the "dimension_signature" field.
	DimensionSignature string `json:"dimension_signature,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ConfigVersion holds the value of the "config_version" field.
	ConfigVersion uint64 `json:"config_version,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// EnabledAt holds the value of the "enabled_at" field.
	EnabledAt *time.Time `json:"enabled_at,omitempty"`
	// DisabledAt holds the value of the "disabled_at" field.
	DisabledAt *time.Time `json:"disabled_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy    uint64 `json:"created_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TokenStatProjection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tokenstatprojection.FieldDimensionCodes:
			values[i] = new([]byte)
		case tokenstatprojection.FieldID, tokenstatprojection.FieldConfigVersion, tokenstatprojection.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case tokenstatprojection.FieldName, tokenstatprojection.FieldDimensionSignature, tokenstatprojection.FieldStatus:
			values[i] = new(sql.NullString)
		case tokenstatprojection.FieldCreatedAt, tokenstatprojection.FieldUpdatedAt, tokenstatprojection.FieldPublishedAt, tokenstatprojection.FieldEnabledAt, tokenstatprojection.FieldDisabledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TokenStatProjection fields.
func (_m *TokenStatProjection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tokenstatprojection.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case tokenstatprojection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tokenstatprojection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case tokenstatprojection.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tokenstatprojection.FieldDimensionCodes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dimension_codes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DimensionCodes); err != nil {
					return fmt.Errorf("unmarshal field dimension_codes: %w", err)
				}
			}
		case tokenstatprojection.FieldDimensionSignature:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dimension_signature", values[i])
			} else if value.Valid {
				_m.DimensionSignature = value.String
			}
		case tokenstatprojection.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case tokenstatprojection.FieldConfigVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field config_version", values[i])
			} else if value.Valid {
				_m.ConfigVersion = uint64(value.Int64)
			}
		case tokenstatprojection.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case tokenstatprojection.FieldEnabledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field enabled_at", values[i])
			} else if value.Valid {
				_m.EnabledAt = new(time.Time)
				*_m.EnabledAt = value.Time
			}
		case tokenstatprojection.FieldDisabledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field disabled_at", values[i])
			} else if value.Valid {
				_m.DisabledAt = new(time.Time)
				*_m.DisabledAt = value.Time
			}
		case tokenstatprojection.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = uint64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TokenStatProjection.
// This includes values selected through modifiers, order, etc.
func (_m *TokenStatProjection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TokenStatProjection.
// Note that you need to call TokenStatProjection.Unwrap() before calling this method if this TokenStatProjection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TokenStatProjection) Update() *TokenStatProjectionUpdateOne {
	return NewTokenStatProjectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TokenStatProjection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TokenStatProjection) Unwrap() *TokenStatProjection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TokenStatProjection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TokenStatProjection) String() string {
	var builder strings.Builder
	builder.WriteString("TokenStatProjection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("dimension_codes=")
	builder.WriteString(fmt.Sprintf("%v", _m.DimensionCodes))
	builder.WriteString(", ")
	builder.WriteString("dimension_signature=")
	builder.WriteString(_m.DimensionSignature)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("config_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigVersion))
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EnabledAt; v != nil {
		builder.WriteString("enabled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DisabledAt; v != nil {
		builder.WriteString("disabled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// TokenStatProjections is a parsable slice of TokenStatProjection.
type TokenStatProjections []*TokenStatProjection
