// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/tokenstataggregate"
)

// TokenStatAggregateUpdate is the builder for updating TokenStatAggregate entities.
type TokenStatAggregateUpdate struct {
	config
	hooks    []Hook
	mutation *TokenStatAggregateMutation
}

// Where appends a list predicates to the TokenStatAggregateUpdate builder.
func (_u *TokenStatAggregateUpdate) Where(ps ...predicate.TokenStatAggregate) *TokenStatAggregateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenStatAggregateUpdate) SetUpdatedAt(v time.Time) *TokenStatAggregateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPeriodType sets the "period_type" field.
func (_u *TokenStatAggregateUpdate) SetPeriodType(v string) *TokenStatAggregateUpdate {
	_u.mutation.SetPeriodType(v)
	return _u
}

// SetNillablePeriodType sets the "period_type" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillablePeriodType(v *string) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetPeriodType(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *TokenStatAggregateUpdate) SetPeriodStart(v time.Time) *TokenStatAggregateUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillablePeriodStart(v *time.Time) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *TokenStatAggregateUpdate) SetPeriodEnd(v time.Time) *TokenStatAggregateUpdate {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillablePeriodEnd(v *time.Time) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetProjectionID sets the "projection_id" field.
func (_u *TokenStatAggregateUpdate) SetProjectionID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.ResetProjectionID()
	_u.mutation.SetProjectionID(v)
	return _u
}

// SetNillableProjectionID sets the "projection_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableProjectionID(v *int64) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetProjectionID(*v)
	}
	return _u
}

// AddProjectionID adds value to the "projection_id" field.
func (_u *TokenStatAggregateUpdate) AddProjectionID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.AddProjectionID(v)
	return _u
}

// SetDimensionHash sets the "dimension_hash" field.
func (_u *TokenStatAggregateUpdate) SetDimensionHash(v []byte) *TokenStatAggregateUpdate {
	_u.mutation.SetDimensionHash(v)
	return _u
}

// SetDimensionValues sets the "dimension_values" field.
func (_u *TokenStatAggregateUpdate) SetDimensionValues(v map[string]interface{}) *TokenStatAggregateUpdate {
	_u.mutation.SetDimensionValues(v)
	return _u
}

// SetMetricCode sets the "metric_code" field.
func (_u *TokenStatAggregateUpdate) SetMetricCode(v string) *TokenStatAggregateUpdate {
	_u.mutation.SetMetricCode(v)
	return _u
}

// SetNillableMetricCode sets the "metric_code" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableMetricCode(v *string) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetMetricCode(*v)
	}
	return _u
}

// SetMetricValue sets the "metric_value" field.
func (_u *TokenStatAggregateUpdate) SetMetricValue(v int64) *TokenStatAggregateUpdate {
	_u.mutation.ResetMetricValue()
	_u.mutation.SetMetricValue(v)
	return _u
}

// SetNillableMetricValue sets the "metric_value" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableMetricValue(v *int64) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetMetricValue(*v)
	}
	return _u
}

// AddMetricValue adds value to the "metric_value" field.
func (_u *TokenStatAggregateUpdate) AddMetricValue(v int64) *TokenStatAggregateUpdate {
	_u.mutation.AddMetricValue(v)
	return _u
}

// SetSourceVersion sets the "source_version" field.
func (_u *TokenStatAggregateUpdate) SetSourceVersion(v int64) *TokenStatAggregateUpdate {
	_u.mutation.ResetSourceVersion()
	_u.mutation.SetSourceVersion(v)
	return _u
}

// SetNillableSourceVersion sets the "source_version" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableSourceVersion(v *int64) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetSourceVersion(*v)
	}
	return _u
}

// AddSourceVersion adds value to the "source_version" field.
func (_u *TokenStatAggregateUpdate) AddSourceVersion(v int64) *TokenStatAggregateUpdate {
	_u.mutation.AddSourceVersion(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TokenStatAggregateUpdate) SetUserID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableUserID(v *int64) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TokenStatAggregateUpdate) AddUserID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *TokenStatAggregateUpdate) ClearUserID() *TokenStatAggregateUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *TokenStatAggregateUpdate) SetAPIKeyID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableAPIKeyID(v *int64) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *TokenStatAggregateUpdate) AddAPIKeyID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *TokenStatAggregateUpdate) ClearAPIKeyID() *TokenStatAggregateUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *TokenStatAggregateUpdate) SetGroupID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableGroupID(v *int64) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *TokenStatAggregateUpdate) AddGroupID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *TokenStatAggregateUpdate) ClearGroupID() *TokenStatAggregateUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetRouteAlias sets the "route_alias" field.
func (_u *TokenStatAggregateUpdate) SetRouteAlias(v string) *TokenStatAggregateUpdate {
	_u.mutation.SetRouteAlias(v)
	return _u
}

// SetNillableRouteAlias sets the "route_alias" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableRouteAlias(v *string) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetRouteAlias(*v)
	}
	return _u
}

// ClearRouteAlias clears the value of the "route_alias" field.
func (_u *TokenStatAggregateUpdate) ClearRouteAlias() *TokenStatAggregateUpdate {
	_u.mutation.ClearRouteAlias()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TokenStatAggregateUpdate) SetAccountID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableAccountID(v *int64) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *TokenStatAggregateUpdate) AddAccountID(v int64) *TokenStatAggregateUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *TokenStatAggregateUpdate) ClearAccountID() *TokenStatAggregateUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *TokenStatAggregateUpdate) SetUpstreamModel(v string) *TokenStatAggregateUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableUpstreamModel(v *string) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (_u *TokenStatAggregateUpdate) ClearUpstreamModel() *TokenStatAggregateUpdate {
	_u.mutation.ClearUpstreamModel()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *TokenStatAggregateUpdate) SetLastSyncedAt(v time.Time) *TokenStatAggregateUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *TokenStatAggregateUpdate) SetNillableLastSyncedAt(v *time.Time) *TokenStatAggregateUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// Mutation returns the TokenStatAggregateMutation object of the builder.
func (_u *TokenStatAggregateUpdate) Mutation() *TokenStatAggregateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TokenStatAggregateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenStatAggregateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TokenStatAggregateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenStatAggregateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenStatAggregateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tokenstataggregate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokenStatAggregateUpdate) check() error {
	if v, ok := _u.mutation.PeriodType(); ok {
		if err := tokenstataggregate.PeriodTypeValidator(v); err != nil {
			return &ValidationError{Name: "period_type", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.period_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProjectionID(); ok {
		if err := tokenstataggregate.ProjectionIDValidator(v); err != nil {
			return &ValidationError{Name: "projection_id", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.projection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetricCode(); ok {
		if err := tokenstataggregate.MetricCodeValidator(v); err != nil {
			return &ValidationError{Name: "metric_code", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.metric_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetricValue(); ok {
		if err := tokenstataggregate.MetricValueValidator(v); err != nil {
			return &ValidationError{Name: "metric_value", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.metric_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceVersion(); ok {
		if err := tokenstataggregate.SourceVersionValidator(v); err != nil {
			return &ValidationError{Name: "source_version", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.source_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteAlias(); ok {
		if err := tokenstataggregate.RouteAliasValidator(v); err != nil {
			return &ValidationError{Name: "route_alias", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.route_alias": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := tokenstataggregate.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.upstream_model": %w`, err)}
		}
	}
	return nil
}

func (_u *TokenStatAggregateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tokenstataggregate.Table, tokenstataggregate.Columns, sqlgraph.NewFieldSpec(tokenstataggregate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenstataggregate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodType(); ok {
		_spec.SetField(tokenstataggregate.FieldPeriodType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(tokenstataggregate.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(tokenstataggregate.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProjectionID(); ok {
		_spec.SetField(tokenstataggregate.FieldProjectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectionID(); ok {
		_spec.AddField(tokenstataggregate.FieldProjectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DimensionHash(); ok {
		_spec.SetField(tokenstataggregate.FieldDimensionHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DimensionValues(); ok {
		_spec.SetField(tokenstataggregate.FieldDimensionValues, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.MetricCode(); ok {
		_spec.SetField(tokenstataggregate.FieldMetricCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetricValue(); ok {
		_spec.SetField(tokenstataggregate.FieldMetricValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetricValue(); ok {
		_spec.AddField(tokenstataggregate.FieldMetricValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceVersion(); ok {
		_spec.SetField(tokenstataggregate.FieldSourceVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceVersion(); ok {
		_spec.AddField(tokenstataggregate.FieldSourceVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(tokenstataggregate.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(tokenstataggregate.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(tokenstataggregate.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(tokenstataggregate.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(tokenstataggregate.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(tokenstataggregate.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(tokenstataggregate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(tokenstataggregate.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(tokenstataggregate.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RouteAlias(); ok {
		_spec.SetField(tokenstataggregate.FieldRouteAlias, field.TypeString, value)
	}
	if _u.mutation.RouteAliasCleared() {
		_spec.ClearField(tokenstataggregate.FieldRouteAlias, field.TypeString)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(tokenstataggregate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(tokenstataggregate.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(tokenstataggregate.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(tokenstataggregate.FieldUpstreamModel, field.TypeString, value)
	}
	if _u.mutation.UpstreamModelCleared() {
		_spec.ClearField(tokenstataggregate.FieldUpstreamModel, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(tokenstataggregate.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokenstataggregate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TokenStatAggregateUpdateOne is the builder for updating a single TokenStatAggregate entity.
type TokenStatAggregateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TokenStatAggregateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenStatAggregateUpdateOne) SetUpdatedAt(v time.Time) *TokenStatAggregateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPeriodType sets the "period_type" field.
func (_u *TokenStatAggregateUpdateOne) SetPeriodType(v string) *TokenStatAggregateUpdateOne {
	_u.mutation.SetPeriodType(v)
	return _u
}

// SetNillablePeriodType sets the "period_type" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillablePeriodType(v *string) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetPeriodType(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *TokenStatAggregateUpdateOne) SetPeriodStart(v time.Time) *TokenStatAggregateUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillablePeriodStart(v *time.Time) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *TokenStatAggregateUpdateOne) SetPeriodEnd(v time.Time) *TokenStatAggregateUpdateOne {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillablePeriodEnd(v *time.Time) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetProjectionID sets the "projection_id" field.
func (_u *TokenStatAggregateUpdateOne) SetProjectionID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.ResetProjectionID()
	_u.mutation.SetProjectionID(v)
	return _u
}

// SetNillableProjectionID sets the "projection_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableProjectionID(v *int64) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetProjectionID(*v)
	}
	return _u
}

// AddProjectionID adds value to the "projection_id" field.
func (_u *TokenStatAggregateUpdateOne) AddProjectionID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.AddProjectionID(v)
	return _u
}

// SetDimensionHash sets the "dimension_hash" field.
func (_u *TokenStatAggregateUpdateOne) SetDimensionHash(v []byte) *TokenStatAggregateUpdateOne {
	_u.mutation.SetDimensionHash(v)
	return _u
}

// SetDimensionValues sets the "dimension_values" field.
func (_u *TokenStatAggregateUpdateOne) SetDimensionValues(v map[string]interface{}) *TokenStatAggregateUpdateOne {
	_u.mutation.SetDimensionValues(v)
	return _u
}

// SetMetricCode sets the "metric_code" field.
func (_u *TokenStatAggregateUpdateOne) SetMetricCode(v string) *TokenStatAggregateUpdateOne {
	_u.mutation.SetMetricCode(v)
	return _u
}

// SetNillableMetricCode sets the "metric_code" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableMetricCode(v *string) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetMetricCode(*v)
	}
	return _u
}

// SetMetricValue sets the "metric_value" field.
func (_u *TokenStatAggregateUpdateOne) SetMetricValue(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.ResetMetricValue()
	_u.mutation.SetMetricValue(v)
	return _u
}

// SetNillableMetricValue sets the "metric_value" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableMetricValue(v *int64) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetMetricValue(*v)
	}
	return _u
}

// AddMetricValue adds value to the "metric_value" field.
func (_u *TokenStatAggregateUpdateOne) AddMetricValue(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.AddMetricValue(v)
	return _u
}

// SetSourceVersion sets the "source_version" field.
func (_u *TokenStatAggregateUpdateOne) SetSourceVersion(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.ResetSourceVersion()
	_u.mutation.SetSourceVersion(v)
	return _u
}

// SetNillableSourceVersion sets the "source_version" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableSourceVersion(v *int64) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetSourceVersion(*v)
	}
	return _u
}

// AddSourceVersion adds value to the "source_version" field.
func (_u *TokenStatAggregateUpdateOne) AddSourceVersion(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.AddSourceVersion(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TokenStatAggregateUpdateOne) SetUserID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableUserID(v *int64) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TokenStatAggregateUpdateOne) AddUserID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *TokenStatAggregateUpdateOne) ClearUserID() *TokenStatAggregateUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *TokenStatAggregateUpdateOne) SetAPIKeyID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableAPIKeyID(v *int64) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *TokenStatAggregateUpdateOne) AddAPIKeyID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *TokenStatAggregateUpdateOne) ClearAPIKeyID() *TokenStatAggregateUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *TokenStatAggregateUpdateOne) SetGroupID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableGroupID(v *int64) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *TokenStatAggregateUpdateOne) AddGroupID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *TokenStatAggregateUpdateOne) ClearGroupID() *TokenStatAggregateUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetRouteAlias sets the "route_alias" field.
func (_u *TokenStatAggregateUpdateOne) SetRouteAlias(v string) *TokenStatAggregateUpdateOne {
	_u.mutation.SetRouteAlias(v)
	return _u
}

// SetNillableRouteAlias sets the "route_alias" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableRouteAlias(v *string) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetRouteAlias(*v)
	}
	return _u
}

// ClearRouteAlias clears the value of the "route_alias" field.
func (_u *TokenStatAggregateUpdateOne) ClearRouteAlias() *TokenStatAggregateUpdateOne {
	_u.mutation.ClearRouteAlias()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TokenStatAggregateUpdateOne) SetAccountID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableAccountID(v *int64) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *TokenStatAggregateUpdateOne) AddAccountID(v int64) *TokenStatAggregateUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *TokenStatAggregateUpdateOne) ClearAccountID() *TokenStatAggregateUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *TokenStatAggregateUpdateOne) SetUpstreamModel(v string) *TokenStatAggregateUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableUpstreamModel(v *string) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (_u *TokenStatAggregateUpdateOne) ClearUpstreamModel() *TokenStatAggregateUpdateOne {
	_u.mutation.ClearUpstreamModel()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *TokenStatAggregateUpdateOne) SetLastSyncedAt(v time.Time) *TokenStatAggregateUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *TokenStatAggregateUpdateOne) SetNillableLastSyncedAt(v *time.Time) *TokenStatAggregateUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// Mutation returns the TokenStatAggregateMutation object of the builder.
func (_u *TokenStatAggregateUpdateOne) Mutation() *TokenStatAggregateMutation {
	return _u.mutation
}

// Where appends a list predicates to the TokenStatAggregateUpdate builder.
func (_u *TokenStatAggregateUpdateOne) Where(ps ...predicate.TokenStatAggregate) *TokenStatAggregateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TokenStatAggregateUpdateOne) Select(field string, fields ...string) *TokenStatAggregateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TokenStatAggregate entity.
func (_u *TokenStatAggregateUpdateOne) Save(ctx context.Context) (*TokenStatAggregate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenStatAggregateUpdateOne) SaveX(ctx context.Context) *TokenStatAggregate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TokenStatAggregateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenStatAggregateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenStatAggregateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tokenstataggregate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokenStatAggregateUpdateOne) check() error {
	if v, ok := _u.mutation.PeriodType(); ok {
		if err := tokenstataggregate.PeriodTypeValidator(v); err != nil {
			return &ValidationError{Name: "period_type", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.period_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProjectionID(); ok {
		if err := tokenstataggregate.ProjectionIDValidator(v); err != nil {
			return &ValidationError{Name: "projection_id", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.projection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetricCode(); ok {
		if err := tokenstataggregate.MetricCodeValidator(v); err != nil {
			return &ValidationError{Name: "metric_code", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.metric_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetricValue(); ok {
		if err := tokenstataggregate.MetricValueValidator(v); err != nil {
			return &ValidationError{Name: "metric_value", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.metric_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceVersion(); ok {
		if err := tokenstataggregate.SourceVersionValidator(v); err != nil {
			return &ValidationError{Name: "source_version", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.source_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RouteAlias(); ok {
		if err := tokenstataggregate.RouteAliasValidator(v); err != nil {
			return &ValidationError{Name: "route_alias", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.route_alias": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := tokenstataggregate.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "TokenStatAggregate.upstream_model": %w`, err)}
		}
	}
	return nil
}

func (_u *TokenStatAggregateUpdateOne) sqlSave(ctx context.Context) (_node *TokenStatAggregate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tokenstataggregate.Table, tokenstataggregate.Columns, sqlgraph.NewFieldSpec(tokenstataggregate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TokenStatAggregate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokenstataggregate.FieldID)
		for _, f := range fields {
			if !tokenstataggregate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tokenstataggregate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenstataggregate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodType(); ok {
		_spec.SetField(tokenstataggregate.FieldPeriodType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(tokenstataggregate.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(tokenstataggregate.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProjectionID(); ok {
		_spec.SetField(tokenstataggregate.FieldProjectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectionID(); ok {
		_spec.AddField(tokenstataggregate.FieldProjectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DimensionHash(); ok {
		_spec.SetField(tokenstataggregate.FieldDimensionHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DimensionValues(); ok {
		_spec.SetField(tokenstataggregate.FieldDimensionValues, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.MetricCode(); ok {
		_spec.SetField(tokenstataggregate.FieldMetricCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetricValue(); ok {
		_spec.SetField(tokenstataggregate.FieldMetricValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetricValue(); ok {
		_spec.AddField(tokenstataggregate.FieldMetricValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceVersion(); ok {
		_spec.SetField(tokenstataggregate.FieldSourceVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceVersion(); ok {
		_spec.AddField(tokenstataggregate.FieldSourceVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(tokenstataggregate.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(tokenstataggregate.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(tokenstataggregate.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(tokenstataggregate.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(tokenstataggregate.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(tokenstataggregate.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(tokenstataggregate.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(tokenstataggregate.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(tokenstataggregate.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RouteAlias(); ok {
		_spec.SetField(tokenstataggregate.FieldRouteAlias, field.TypeString, value)
	}
	if _u.mutation.RouteAliasCleared() {
		_spec.ClearField(tokenstataggregate.FieldRouteAlias, field.TypeString)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(tokenstataggregate.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(tokenstataggregate.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(tokenstataggregate.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(tokenstataggregate.FieldUpstreamModel, field.TypeString, value)
	}
	if _u.mutation.UpstreamModelCleared() {
		_spec.ClearField(tokenstataggregate.FieldUpstreamModel, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(tokenstataggregate.FieldLastSyncedAt, field.TypeTime, value)
	}
	_node = &TokenStatAggregate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokenstataggregate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
