// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/tokenstatprojectionmetric"
)

// TokenStatProjectionMetric is the model entity for the TokenStatProjectionMetric schema.
type TokenStatProjectionMetric struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProjectionID holds the value of the "projection_id" field.
	ProjectionID int64 `json:"projection_id,omitempty"`
	// MetricCode holds the value of the "metric_code" field.
	MetricCode string `json:"metric_code,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// EnabledAt holds the value of the "enabled_at" field.
	EnabledAt *time.Time `json:"enabled_at,omitempty"`
	// DisabledAt holds the value of the "disabled_at" field.
	DisabledAt   *time.Time `json:"disabled_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TokenStatProjectionMetric) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tokenstatprojectionmetric.FieldID, tokenstatprojectionmetric.FieldProjectionID:
			values[i] = new(sql.NullInt64)
		case tokenstatprojectionmetric.FieldMetricCode, tokenstatprojectionmetric.FieldStatus:
			values[i] = new(sql.NullString)
		case tokenstatprojectionmetric.FieldCreatedAt, tokenstatprojectionmetric.FieldUpdatedAt, tokenstatprojectionmetric.FieldEnabledAt, tokenstatprojectionmetric.FieldDisabledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TokenStatProjectionMetric fields.
func (_m *TokenStatProjectionMetric) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tokenstatprojectionmetric.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case tokenstatprojectionmetric.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tokenstatprojectionmetric.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case tokenstatprojectionmetric.FieldProjectionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field projection_id", values[i])
			} else if value.Valid {
				_m.ProjectionID = value.Int64
			}
		case tokenstatprojectionmetric.FieldMetricCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metric_code", values[i])
			} else if value.Valid {
				_m.MetricCode = value.String
			}
		case tokenstatprojectionmetric.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case tokenstatprojectionmetric.FieldEnabledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field enabled_at", values[i])
			} else if value.Valid {
				_m.EnabledAt = new(time.Time)
				*_m.EnabledAt = value.Time
			}
		case tokenstatprojectionmetric.FieldDisabledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field disabled_at", values[i])
			} else if value.Valid {
				_m.DisabledAt = new(time.Time)
				*_m.DisabledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TokenStatProjectionMetric.
// This includes values selected through modifiers, order, etc.
func (_m *TokenStatProjectionMetric) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TokenStatProjectionMetric.
// Note that you need to call TokenStatProjectionMetric.Unwrap() before calling this method if this TokenStatProjectionMetric
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TokenStatProjectionMetric) Update() *TokenStatProjectionMetricUpdateOne {
	return NewTokenStatProjectionMetricClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TokenStatProjectionMetric entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TokenStatProjectionMetric) Unwrap() *TokenStatProjectionMetric {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TokenStatProjectionMetric is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TokenStatProjectionMetric) String() string {
	var builder strings.Builder
	builder.WriteString("TokenStatProjectionMetric(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("projection_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectionID))
	builder.WriteString(", ")
	builder.WriteString("metric_code=")
	builder.WriteString(_m.MetricCode)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.EnabledAt; v != nil {
		builder.WriteString("enabled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DisabledAt; v != nil {
		builder.WriteString("disabled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// TokenStatProjectionMetrics is a parsable slice of TokenStatProjectionMetric.
type TokenStatProjectionMetrics []*TokenStatProjectionMetric
