// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/tokenstatprojection"
)

// TokenStatProjectionUpdate is the builder for updating TokenStatProjection entities.
type TokenStatProjectionUpdate struct {
	config
	hooks    []Hook
	mutation *TokenStatProjectionMutation
}

// Where appends a list predicates to the TokenStatProjectionUpdate builder.
func (_u *TokenStatProjectionUpdate) Where(ps ...predicate.TokenStatProjection) *TokenStatProjectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenStatProjectionUpdate) SetUpdatedAt(v time.Time) *TokenStatProjectionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TokenStatProjectionUpdate) SetName(v string) *TokenStatProjectionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TokenStatProjectionUpdate) SetNillableName(v *string) *TokenStatProjectionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDimensionCodes sets the "dimension_codes" field.
func (_u *TokenStatProjectionUpdate) SetDimensionCodes(v []string) *TokenStatProjectionUpdate {
	_u.mutation.SetDimensionCodes(v)
	return _u
}

// AppendDimensionCodes appends value to the "dimension_codes" field.
func (_u *TokenStatProjectionUpdate) AppendDimensionCodes(v []string) *TokenStatProjectionUpdate {
	_u.mutation.AppendDimensionCodes(v)
	return _u
}

// SetDimensionSignature sets the "dimension_signature" field.
func (_u *TokenStatProjectionUpdate) SetDimensionSignature(v string) *TokenStatProjectionUpdate {
	_u.mutation.SetDimensionSignature(v)
	return _u
}

// SetNillableDimensionSignature sets the "dimension_signature" field if the given value is not nil.
func (_u *TokenStatProjectionUpdate) SetNillableDimensionSignature(v *string) *TokenStatProjectionUpdate {
	if v != nil {
		_u.SetDimensionSignature(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TokenStatProjectionUpdate) SetStatus(v string) *TokenStatProjectionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TokenStatProjectionUpdate) SetNillableStatus(v *string) *TokenStatProjectionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfigVersion sets the "config_version" field.
func (_u *TokenStatProjectionUpdate) SetConfigVersion(v uint64) *TokenStatProjectionUpdate {
	_u.mutation.ResetConfigVersion()
	_u.mutation.SetConfigVersion(v)
	return _u
}

// SetNillableConfigVersion sets the "config_version" field if the given value is not nil.
func (_u *TokenStatProjectionUpdate) SetNillableConfigVersion(v *uint64) *TokenStatProjectionUpdate {
	if v != nil {
		_u.SetConfigVersion(*v)
	}
	return _u
}

// AddConfigVersion adds value to the "config_version" field.
func (_u *TokenStatProjectionUpdate) AddConfigVersion(v int64) *TokenStatProjectionUpdate {
	_u.mutation.AddConfigVersion(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *TokenStatProjectionUpdate) SetPublishedAt(v time.Time) *TokenStatProjectionUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *TokenStatProjectionUpdate) SetNillablePublishedAt(v *time.Time) *TokenStatProjectionUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *TokenStatProjectionUpdate) ClearPublishedAt() *TokenStatProjectionUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetEnabledAt sets the "enabled_at" field.
func (_u *TokenStatProjectionUpdate) SetEnabledAt(v time.Time) *TokenStatProjectionUpdate {
	_u.mutation.SetEnabledAt(v)
	return _u
}

// SetNillableEnabledAt sets the "enabled_at" field if the given value is not nil.
func (_u *TokenStatProjectionUpdate) SetNillableEnabledAt(v *time.Time) *TokenStatProjectionUpdate {
	if v != nil {
		_u.SetEnabledAt(*v)
	}
	return _u
}

// ClearEnabledAt clears the value of the "enabled_at" field.
func (_u *TokenStatProjectionUpdate) ClearEnabledAt() *TokenStatProjectionUpdate {
	_u.mutation.ClearEnabledAt()
	return _u
}

// SetDisabledAt sets the "disabled_at" field.
func (_u *TokenStatProjectionUpdate) SetDisabledAt(v time.Time) *TokenStatProjectionUpdate {
	_u.mutation.SetDisabledAt(v)
	return _u
}

// SetNillableDisabledAt sets the "disabled_at" field if the given value is not nil.
func (_u *TokenStatProjectionUpdate) SetNillableDisabledAt(v *time.Time) *TokenStatProjectionUpdate {
	if v != nil {
		_u.SetDisabledAt(*v)
	}
	return _u
}

// ClearDisabledAt clears the value of the "disabled_at" field.
func (_u *TokenStatProjectionUpdate) ClearDisabledAt() *TokenStatProjectionUpdate {
	_u.mutation.ClearDisabledAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TokenStatProjectionUpdate) SetCreatedBy(v uint64) *TokenStatProjectionUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TokenStatProjectionUpdate) SetNillableCreatedBy(v *uint64) *TokenStatProjectionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TokenStatProjectionUpdate) AddCreatedBy(v int64) *TokenStatProjectionUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the TokenStatProjectionMutation object of the builder.
func (_u *TokenStatProjectionUpdate) Mutation() *TokenStatProjectionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TokenStatProjectionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenStatProjectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TokenStatProjectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenStatProjectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenStatProjectionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tokenstatprojection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokenStatProjectionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tokenstatprojection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TokenStatProjection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DimensionSignature(); ok {
		if err := tokenstatprojection.DimensionSignatureValidator(v); err != nil {
			return &ValidationError{Name: "dimension_signature", err: fmt.Errorf(`ent: validator failed for field "TokenStatProjection.dimension_signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tokenstatprojection.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TokenStatProjection.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TokenStatProjectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tokenstatprojection.Table, tokenstatprojection.Columns, sqlgraph.NewFieldSpec(tokenstatprojection.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenstatprojection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tokenstatprojection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DimensionCodes(); ok {
		_spec.SetField(tokenstatprojection.FieldDimensionCodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDimensionCodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tokenstatprojection.FieldDimensionCodes, value)
		})
	}
	if value, ok := _u.mutation.DimensionSignature(); ok {
		_spec.SetField(tokenstatprojection.FieldDimensionSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tokenstatprojection.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigVersion(); ok {
		_spec.SetField(tokenstatprojection.FieldConfigVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedConfigVersion(); ok {
		_spec.AddField(tokenstatprojection.FieldConfigVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(tokenstatprojection.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(tokenstatprojection.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EnabledAt(); ok {
		_spec.SetField(tokenstatprojection.FieldEnabledAt, field.TypeTime, value)
	}
	if _u.mutation.EnabledAtCleared() {
		_spec.ClearField(tokenstatprojection.FieldEnabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DisabledAt(); ok {
		_spec.SetField(tokenstatprojection.FieldDisabledAt, field.TypeTime, value)
	}
	if _u.mutation.DisabledAtCleared() {
		_spec.ClearField(tokenstatprojection.FieldDisabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tokenstatprojection.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(tokenstatprojection.FieldCreatedBy, field.TypeUint64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokenstatprojection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TokenStatProjectionUpdateOne is the builder for updating a single TokenStatProjection entity.
type TokenStatProjectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TokenStatProjectionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenStatProjectionUpdateOne) SetUpdatedAt(v time.Time) *TokenStatProjectionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TokenStatProjectionUpdateOne) SetName(v string) *TokenStatProjectionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TokenStatProjectionUpdateOne) SetNillableName(v *string) *TokenStatProjectionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDimensionCodes sets the "dimension_codes" field.
func (_u *TokenStatProjectionUpdateOne) SetDimensionCodes(v []string) *TokenStatProjectionUpdateOne {
	_u.mutation.SetDimensionCodes(v)
	return _u
}

// AppendDimensionCodes appends value to the "dimension_codes" field.
func (_u *TokenStatProjectionUpdateOne) AppendDimensionCodes(v []string) *TokenStatProjectionUpdateOne {
	_u.mutation.AppendDimensionCodes(v)
	return _u
}

// SetDimensionSignature sets the "dimension_signature" field.
func (_u *TokenStatProjectionUpdateOne) SetDimensionSignature(v string) *TokenStatProjectionUpdateOne {
	_u.mutation.SetDimensionSignature(v)
	return _u
}

// SetNillableDimensionSignature sets the "dimension_signature" field if the given value is not nil.
func (_u *TokenStatProjectionUpdateOne) SetNillableDimensionSignature(v *string) *TokenStatProjectionUpdateOne {
	if v != nil {
		_u.SetDimensionSignature(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TokenStatProjectionUpdateOne) SetStatus(v string) *TokenStatProjectionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TokenStatProjectionUpdateOne) SetNillableStatus(v *string) *TokenStatProjectionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfigVersion sets the "config_version" field.
func (_u *TokenStatProjectionUpdateOne) SetConfigVersion(v uint64) *TokenStatProjectionUpdateOne {
	_u.mutation.ResetConfigVersion()
	_u.mutation.SetConfigVersion(v)
	return _u
}

// SetNillableConfigVersion sets the "config_version" field if the given value is not nil.
func (_u *TokenStatProjectionUpdateOne) SetNillableConfigVersion(v *uint64) *TokenStatProjectionUpdateOne {
	if v != nil {
		_u.SetConfigVersion(*v)
	}
	return _u
}

// AddConfigVersion adds value to the "config_version" field.
func (_u *TokenStatProjectionUpdateOne) AddConfigVersion(v int64) *TokenStatProjectionUpdateOne {
	_u.mutation.AddConfigVersion(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *TokenStatProjectionUpdateOne) SetPublishedAt(v time.Time) *TokenStatProjectionUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *TokenStatProjectionUpdateOne) SetNillablePublishedAt(v *time.Time) *TokenStatProjectionUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *TokenStatProjectionUpdateOne) ClearPublishedAt() *TokenStatProjectionUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetEnabledAt sets the "enabled_at" field.
func (_u *TokenStatProjectionUpdateOne) SetEnabledAt(v time.Time) *TokenStatProjectionUpdateOne {
	_u.mutation.SetEnabledAt(v)
	return _u
}

// SetNillableEnabledAt sets the "enabled_at" field if the given value is not nil.
func (_u *TokenStatProjectionUpdateOne) SetNillableEnabledAt(v *time.Time) *TokenStatProjectionUpdateOne {
	if v != nil {
		_u.SetEnabledAt(*v)
	}
	return _u
}

// ClearEnabledAt clears the value of the "enabled_at" field.
func (_u *TokenStatProjectionUpdateOne) ClearEnabledAt() *TokenStatProjectionUpdateOne {
	_u.mutation.ClearEnabledAt()
	return _u
}

// SetDisabledAt sets the "disabled_at" field.
func (_u *TokenStatProjectionUpdateOne) SetDisabledAt(v time.Time) *TokenStatProjectionUpdateOne {
	_u.mutation.SetDisabledAt(v)
	return _u
}

// SetNillableDisabledAt sets the "disabled_at" field if the given value is not nil.
func (_u *TokenStatProjectionUpdateOne) SetNillableDisabledAt(v *time.Time) *TokenStatProjectionUpdateOne {
	if v != nil {
		_u.SetDisabledAt(*v)
	}
	return _u
}

// ClearDisabledAt clears the value of the "disabled_at" field.
func (_u *TokenStatProjectionUpdateOne) ClearDisabledAt() *TokenStatProjectionUpdateOne {
	_u.mutation.ClearDisabledAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TokenStatProjectionUpdateOne) SetCreatedBy(v uint64) *TokenStatProjectionUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TokenStatProjectionUpdateOne) SetNillableCreatedBy(v *uint64) *TokenStatProjectionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TokenStatProjectionUpdateOne) AddCreatedBy(v int64) *TokenStatProjectionUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the TokenStatProjectionMutation object of the builder.
func (_u *TokenStatProjectionUpdateOne) Mutation() *TokenStatProjectionMutation {
	return _u.mutation
}

// Where appends a list predicates to the TokenStatProjectionUpdate builder.
func (_u *TokenStatProjectionUpdateOne) Where(ps ...predicate.TokenStatProjection) *TokenStatProjectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TokenStatProjectionUpdateOne) Select(field string, fields ...string) *TokenStatProjectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TokenStatProjection entity.
func (_u *TokenStatProjectionUpdateOne) Save(ctx context.Context) (*TokenStatProjection, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenStatProjectionUpdateOne) SaveX(ctx context.Context) *TokenStatProjection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TokenStatProjectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenStatProjectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenStatProjectionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tokenstatprojection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokenStatProjectionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tokenstatprojection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TokenStatProjection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DimensionSignature(); ok {
		if err := tokenstatprojection.DimensionSignatureValidator(v); err != nil {
			return &ValidationError{Name: "dimension_signature", err: fmt.Errorf(`ent: validator failed for field "TokenStatProjection.dimension_signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tokenstatprojection.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TokenStatProjection.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TokenStatProjectionUpdateOne) sqlSave(ctx context.Context) (_node *TokenStatProjection, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tokenstatprojection.Table, tokenstatprojection.Columns, sqlgraph.NewFieldSpec(tokenstatprojection.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TokenStatProjection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokenstatprojection.FieldID)
		for _, f := range fields {
			if !tokenstatprojection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tokenstatprojection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenstatprojection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tokenstatprojection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DimensionCodes(); ok {
		_spec.SetField(tokenstatprojection.FieldDimensionCodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDimensionCodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tokenstatprojection.FieldDimensionCodes, value)
		})
	}
	if value, ok := _u.mutation.DimensionSignature(); ok {
		_spec.SetField(tokenstatprojection.FieldDimensionSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tokenstatprojection.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigVersion(); ok {
		_spec.SetField(tokenstatprojection.FieldConfigVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedConfigVersion(); ok {
		_spec.AddField(tokenstatprojection.FieldConfigVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(tokenstatprojection.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(tokenstatprojection.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EnabledAt(); ok {
		_spec.SetField(tokenstatprojection.FieldEnabledAt, field.TypeTime, value)
	}
	if _u.mutation.EnabledAtCleared() {
		_spec.ClearField(tokenstatprojection.FieldEnabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DisabledAt(); ok {
		_spec.SetField(tokenstatprojection.FieldDisabledAt, field.TypeTime, value)
	}
	if _u.mutation.DisabledAtCleared() {
		_spec.ClearField(tokenstatprojection.FieldDisabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tokenstatprojection.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(tokenstatprojection.FieldCreatedBy, field.TypeUint64, value)
	}
	_node = &TokenStatProjection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokenstatprojection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
