// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/tokenstatquotarule"
)

// TokenStatQuotaRuleUpdate is the builder for updating TokenStatQuotaRule entities.
type TokenStatQuotaRuleUpdate struct {
	config
	hooks    []Hook
	mutation *TokenStatQuotaRuleMutation
}

// Where appends a list predicates to the TokenStatQuotaRuleUpdate builder.
func (_u *TokenStatQuotaRuleUpdate) Where(ps ...predicate.TokenStatQuotaRule) *TokenStatQuotaRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenStatQuotaRuleUpdate) SetUpdatedAt(v time.Time) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TokenStatQuotaRuleUpdate) SetName(v string) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillableName(v *string) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProjectionID sets the "projection_id" field.
func (_u *TokenStatQuotaRuleUpdate) SetProjectionID(v int64) *TokenStatQuotaRuleUpdate {
	_u.mutation.ResetProjectionID()
	_u.mutation.SetProjectionID(v)
	return _u
}

// SetNillableProjectionID sets the "projection_id" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillableProjectionID(v *int64) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetProjectionID(*v)
	}
	return _u
}

// AddProjectionID adds value to the "projection_id" field.
func (_u *TokenStatQuotaRuleUpdate) AddProjectionID(v int64) *TokenStatQuotaRuleUpdate {
	_u.mutation.AddProjectionID(v)
	return _u
}

// SetDimensionHash sets the "dimension_hash" field.
func (_u *TokenStatQuotaRuleUpdate) SetDimensionHash(v []byte) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetDimensionHash(v)
	return _u
}

// SetDimensionValues sets the "dimension_values" field.
func (_u *TokenStatQuotaRuleUpdate) SetDimensionValues(v map[string]interface{}) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetDimensionValues(v)
	return _u
}

// SetMetricCode sets the "metric_code" field.
func (_u *TokenStatQuotaRuleUpdate) SetMetricCode(v string) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetMetricCode(v)
	return _u
}

// SetNillableMetricCode sets the "metric_code" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillableMetricCode(v *string) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetMetricCode(*v)
	}
	return _u
}

// SetPeriodType sets the "period_type" field.
func (_u *TokenStatQuotaRuleUpdate) SetPeriodType(v string) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetPeriodType(v)
	return _u
}

// SetNillablePeriodType sets the "period_type" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillablePeriodType(v *string) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetPeriodType(*v)
	}
	return _u
}

// SetLimitValue sets the "limit_value" field.
func (_u *TokenStatQuotaRuleUpdate) SetLimitValue(v int64) *TokenStatQuotaRuleUpdate {
	_u.mutation.ResetLimitValue()
	_u.mutation.SetLimitValue(v)
	return _u
}

// SetNillableLimitValue sets the "limit_value" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillableLimitValue(v *int64) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetLimitValue(*v)
	}
	return _u
}

// AddLimitValue adds value to the "limit_value" field.
func (_u *TokenStatQuotaRuleUpdate) AddLimitValue(v int64) *TokenStatQuotaRuleUpdate {
	_u.mutation.AddLimitValue(v)
	return _u
}

// SetEnforcementMode sets the "enforcement_mode" field.
func (_u *TokenStatQuotaRuleUpdate) SetEnforcementMode(v string) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetEnforcementMode(v)
	return _u
}

// SetNillableEnforcementMode sets the "enforcement_mode" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillableEnforcementMode(v *string) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetEnforcementMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TokenStatQuotaRuleUpdate) SetStatus(v string) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillableStatus(v *string) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *TokenStatQuotaRuleUpdate) SetEffectiveFrom(v time.Time) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillableEffectiveFrom(v *time.Time) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// ClearEffectiveFrom clears the value of the "effective_from" field.
func (_u *TokenStatQuotaRuleUpdate) ClearEffectiveFrom() *TokenStatQuotaRuleUpdate {
	_u.mutation.ClearEffectiveFrom()
	return _u
}

// SetEffectiveUntil sets the "effective_until" field.
func (_u *TokenStatQuotaRuleUpdate) SetEffectiveUntil(v time.Time) *TokenStatQuotaRuleUpdate {
	_u.mutation.SetEffectiveUntil(v)
	return _u
}

// SetNillableEffectiveUntil sets the "effective_until" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillableEffectiveUntil(v *time.Time) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetEffectiveUntil(*v)
	}
	return _u
}

// ClearEffectiveUntil clears the value of the "effective_until" field.
func (_u *TokenStatQuotaRuleUpdate) ClearEffectiveUntil() *TokenStatQuotaRuleUpdate {
	_u.mutation.ClearEffectiveUntil()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TokenStatQuotaRuleUpdate) SetCreatedBy(v uint64) *TokenStatQuotaRuleUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdate) SetNillableCreatedBy(v *uint64) *TokenStatQuotaRuleUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TokenStatQuotaRuleUpdate) AddCreatedBy(v int64) *TokenStatQuotaRuleUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the TokenStatQuotaRuleMutation object of the builder.
func (_u *TokenStatQuotaRuleUpdate) Mutation() *TokenStatQuotaRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TokenStatQuotaRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenStatQuotaRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TokenStatQuotaRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenStatQuotaRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenStatQuotaRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tokenstatquotarule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokenStatQuotaRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tokenstatquotarule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProjectionID(); ok {
		if err := tokenstatquotarule.ProjectionIDValidator(v); err != nil {
			return &ValidationError{Name: "projection_id", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.projection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetricCode(); ok {
		if err := tokenstatquotarule.MetricCodeValidator(v); err != nil {
			return &ValidationError{Name: "metric_code", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.metric_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeriodType(); ok {
		if err := tokenstatquotarule.PeriodTypeValidator(v); err != nil {
			return &ValidationError{Name: "period_type", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.period_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LimitValue(); ok {
		if err := tokenstatquotarule.LimitValueValidator(v); err != nil {
			return &ValidationError{Name: "limit_value", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.limit_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnforcementMode(); ok {
		if err := tokenstatquotarule.EnforcementModeValidator(v); err != nil {
			return &ValidationError{Name: "enforcement_mode", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.enforcement_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tokenstatquotarule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TokenStatQuotaRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tokenstatquotarule.Table, tokenstatquotarule.Columns, sqlgraph.NewFieldSpec(tokenstatquotarule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenstatquotarule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tokenstatquotarule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectionID(); ok {
		_spec.SetField(tokenstatquotarule.FieldProjectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectionID(); ok {
		_spec.AddField(tokenstatquotarule.FieldProjectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DimensionHash(); ok {
		_spec.SetField(tokenstatquotarule.FieldDimensionHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DimensionValues(); ok {
		_spec.SetField(tokenstatquotarule.FieldDimensionValues, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.MetricCode(); ok {
		_spec.SetField(tokenstatquotarule.FieldMetricCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodType(); ok {
		_spec.SetField(tokenstatquotarule.FieldPeriodType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LimitValue(); ok {
		_spec.SetField(tokenstatquotarule.FieldLimitValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLimitValue(); ok {
		_spec.AddField(tokenstatquotarule.FieldLimitValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EnforcementMode(); ok {
		_spec.SetField(tokenstatquotarule.FieldEnforcementMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tokenstatquotarule.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(tokenstatquotarule.FieldEffectiveFrom, field.TypeTime, value)
	}
	if _u.mutation.EffectiveFromCleared() {
		_spec.ClearField(tokenstatquotarule.FieldEffectiveFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.EffectiveUntil(); ok {
		_spec.SetField(tokenstatquotarule.FieldEffectiveUntil, field.TypeTime, value)
	}
	if _u.mutation.EffectiveUntilCleared() {
		_spec.ClearField(tokenstatquotarule.FieldEffectiveUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tokenstatquotarule.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(tokenstatquotarule.FieldCreatedBy, field.TypeUint64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokenstatquotarule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TokenStatQuotaRuleUpdateOne is the builder for updating a single TokenStatQuotaRule entity.
type TokenStatQuotaRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TokenStatQuotaRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetUpdatedAt(v time.Time) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetName(v string) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillableName(v *string) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProjectionID sets the "projection_id" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetProjectionID(v int64) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.ResetProjectionID()
	_u.mutation.SetProjectionID(v)
	return _u
}

// SetNillableProjectionID sets the "projection_id" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillableProjectionID(v *int64) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetProjectionID(*v)
	}
	return _u
}

// AddProjectionID adds value to the "projection_id" field.
func (_u *TokenStatQuotaRuleUpdateOne) AddProjectionID(v int64) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.AddProjectionID(v)
	return _u
}

// SetDimensionHash sets the "dimension_hash" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetDimensionHash(v []byte) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetDimensionHash(v)
	return _u
}

// SetDimensionValues sets the "dimension_values" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetDimensionValues(v map[string]interface{}) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetDimensionValues(v)
	return _u
}

// SetMetricCode sets the "metric_code" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetMetricCode(v string) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetMetricCode(v)
	return _u
}

// SetNillableMetricCode sets the "metric_code" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillableMetricCode(v *string) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetMetricCode(*v)
	}
	return _u
}

// SetPeriodType sets the "period_type" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetPeriodType(v string) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetPeriodType(v)
	return _u
}

// SetNillablePeriodType sets the "period_type" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillablePeriodType(v *string) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetPeriodType(*v)
	}
	return _u
}

// SetLimitValue sets the "limit_value" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetLimitValue(v int64) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.ResetLimitValue()
	_u.mutation.SetLimitValue(v)
	return _u
}

// SetNillableLimitValue sets the "limit_value" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillableLimitValue(v *int64) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetLimitValue(*v)
	}
	return _u
}

// AddLimitValue adds value to the "limit_value" field.
func (_u *TokenStatQuotaRuleUpdateOne) AddLimitValue(v int64) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.AddLimitValue(v)
	return _u
}

// SetEnforcementMode sets the "enforcement_mode" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetEnforcementMode(v string) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetEnforcementMode(v)
	return _u
}

// SetNillableEnforcementMode sets the "enforcement_mode" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillableEnforcementMode(v *string) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetEnforcementMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetStatus(v string) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillableStatus(v *string) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetEffectiveFrom(v time.Time) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillableEffectiveFrom(v *time.Time) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// ClearEffectiveFrom clears the value of the "effective_from" field.
func (_u *TokenStatQuotaRuleUpdateOne) ClearEffectiveFrom() *TokenStatQuotaRuleUpdateOne {
	_u.mutation.ClearEffectiveFrom()
	return _u
}

// SetEffectiveUntil sets the "effective_until" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetEffectiveUntil(v time.Time) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.SetEffectiveUntil(v)
	return _u
}

// SetNillableEffectiveUntil sets the "effective_until" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillableEffectiveUntil(v *time.Time) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetEffectiveUntil(*v)
	}
	return _u
}

// ClearEffectiveUntil clears the value of the "effective_until" field.
func (_u *TokenStatQuotaRuleUpdateOne) ClearEffectiveUntil() *TokenStatQuotaRuleUpdateOne {
	_u.mutation.ClearEffectiveUntil()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TokenStatQuotaRuleUpdateOne) SetCreatedBy(v uint64) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TokenStatQuotaRuleUpdateOne) SetNillableCreatedBy(v *uint64) *TokenStatQuotaRuleUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TokenStatQuotaRuleUpdateOne) AddCreatedBy(v int64) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the TokenStatQuotaRuleMutation object of the builder.
func (_u *TokenStatQuotaRuleUpdateOne) Mutation() *TokenStatQuotaRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the TokenStatQuotaRuleUpdate builder.
func (_u *TokenStatQuotaRuleUpdateOne) Where(ps ...predicate.TokenStatQuotaRule) *TokenStatQuotaRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TokenStatQuotaRuleUpdateOne) Select(field string, fields ...string) *TokenStatQuotaRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TokenStatQuotaRule entity.
func (_u *TokenStatQuotaRuleUpdateOne) Save(ctx context.Context) (*TokenStatQuotaRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenStatQuotaRuleUpdateOne) SaveX(ctx context.Context) *TokenStatQuotaRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TokenStatQuotaRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenStatQuotaRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TokenStatQuotaRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tokenstatquotarule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokenStatQuotaRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tokenstatquotarule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProjectionID(); ok {
		if err := tokenstatquotarule.ProjectionIDValidator(v); err != nil {
			return &ValidationError{Name: "projection_id", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.projection_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetricCode(); ok {
		if err := tokenstatquotarule.MetricCodeValidator(v); err != nil {
			return &ValidationError{Name: "metric_code", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.metric_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PeriodType(); ok {
		if err := tokenstatquotarule.PeriodTypeValidator(v); err != nil {
			return &ValidationError{Name: "period_type", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.period_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LimitValue(); ok {
		if err := tokenstatquotarule.LimitValueValidator(v); err != nil {
			return &ValidationError{Name: "limit_value", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.limit_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EnforcementMode(); ok {
		if err := tokenstatquotarule.EnforcementModeValidator(v); err != nil {
			return &ValidationError{Name: "enforcement_mode", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.enforcement_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tokenstatquotarule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TokenStatQuotaRule.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TokenStatQuotaRuleUpdateOne) sqlSave(ctx context.Context) (_node *TokenStatQuotaRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tokenstatquotarule.Table, tokenstatquotarule.Columns, sqlgraph.NewFieldSpec(tokenstatquotarule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TokenStatQuotaRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokenstatquotarule.FieldID)
		for _, f := range fields {
			if !tokenstatquotarule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tokenstatquotarule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenstatquotarule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tokenstatquotarule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectionID(); ok {
		_spec.SetField(tokenstatquotarule.FieldProjectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectionID(); ok {
		_spec.AddField(tokenstatquotarule.FieldProjectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DimensionHash(); ok {
		_spec.SetField(tokenstatquotarule.FieldDimensionHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DimensionValues(); ok {
		_spec.SetField(tokenstatquotarule.FieldDimensionValues, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.MetricCode(); ok {
		_spec.SetField(tokenstatquotarule.FieldMetricCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodType(); ok {
		_spec.SetField(tokenstatquotarule.FieldPeriodType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LimitValue(); ok {
		_spec.SetField(tokenstatquotarule.FieldLimitValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLimitValue(); ok {
		_spec.AddField(tokenstatquotarule.FieldLimitValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EnforcementMode(); ok {
		_spec.SetField(tokenstatquotarule.FieldEnforcementMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tokenstatquotarule.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(tokenstatquotarule.FieldEffectiveFrom, field.TypeTime, value)
	}
	if _u.mutation.EffectiveFromCleared() {
		_spec.ClearField(tokenstatquotarule.FieldEffectiveFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.EffectiveUntil(); ok {
		_spec.SetField(tokenstatquotarule.FieldEffectiveUntil, field.TypeTime, value)
	}
	if _u.mutation.EffectiveUntilCleared() {
		_spec.ClearField(tokenstatquotarule.FieldEffectiveUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tokenstatquotarule.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(tokenstatquotarule.FieldCreatedBy, field.TypeUint64, value)
	}
	_node = &TokenStatQuotaRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokenstatquotarule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
