// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usermodeltokendailylimitconfig"
)

// UserModelTokenDailyLimitConfig is the model entity for the UserModelTokenDailyLimitConfig schema.
type UserModelTokenDailyLimitConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// DailyLimitTokens holds the value of the "daily_limit_tokens" field.
	DailyLimitTokens *int64 `json:"daily_limit_tokens,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserModelTokenDailyLimitConfigQuery when eager-loading is set.
	Edges        UserModelTokenDailyLimitConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserModelTokenDailyLimitConfigEdges holds the relations/edges for other nodes in the graph.
type UserModelTokenDailyLimitConfigEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserModelTokenDailyLimitConfigEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserModelTokenDailyLimitConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usermodeltokendailylimitconfig.FieldID, usermodeltokendailylimitconfig.FieldUserID, usermodeltokendailylimitconfig.FieldDailyLimitTokens:
			values[i] = new(sql.NullInt64)
		case usermodeltokendailylimitconfig.FieldModel:
			values[i] = new(sql.NullString)
		case usermodeltokendailylimitconfig.FieldCreatedAt, usermodeltokendailylimitconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserModelTokenDailyLimitConfig fields.
func (_m *UserModelTokenDailyLimitConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usermodeltokendailylimitconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usermodeltokendailylimitconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usermodeltokendailylimitconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usermodeltokendailylimitconfig.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usermodeltokendailylimitconfig.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case usermodeltokendailylimitconfig.FieldDailyLimitTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_tokens", values[i])
			} else if value.Valid {
				_m.DailyLimitTokens = new(int64)
				*_m.DailyLimitTokens = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserModelTokenDailyLimitConfig.
// This includes values selected through modifiers, order, etc.
func (_m *UserModelTokenDailyLimitConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserModelTokenDailyLimitConfig entity.
func (_m *UserModelTokenDailyLimitConfig) QueryUser() *UserQuery {
	return NewUserModelTokenDailyLimitConfigClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserModelTokenDailyLimitConfig.
// Note that you need to call UserModelTokenDailyLimitConfig.Unwrap() before calling this method if this UserModelTokenDailyLimitConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserModelTokenDailyLimitConfig) Update() *UserModelTokenDailyLimitConfigUpdateOne {
	return NewUserModelTokenDailyLimitConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserModelTokenDailyLimitConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserModelTokenDailyLimitConfig) Unwrap() *UserModelTokenDailyLimitConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserModelTokenDailyLimitConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserModelTokenDailyLimitConfig) String() string {
	var builder strings.Builder
	builder.WriteString("UserModelTokenDailyLimitConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	if v := _m.DailyLimitTokens; v != nil {
		builder.WriteString("daily_limit_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserModelTokenDailyLimitConfigs is a parsable slice of UserModelTokenDailyLimitConfig.
type UserModelTokenDailyLimitConfigs []*UserModelTokenDailyLimitConfig
