// Code generated by ent, DO NOT EDIT.

package modeltokendailylimitconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modeltokendailylimitconfig type in the database.
	Label = "model_token_daily_limit_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldDailyLimitTokens holds the string denoting the daily_limit_tokens field in the database.
	FieldDailyLimitTokens = "daily_limit_tokens"
	// Table holds the table name of the modeltokendailylimitconfig in the database.
	Table = "model_token_daily_limit_configs"
)

// Columns holds all SQL columns for modeltokendailylimitconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldModel,
	FieldDailyLimitTokens,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DailyLimitTokensValidator is a validator for the "daily_limit_tokens" field. It is called by the builders before save.
	DailyLimitTokensValidator func(int64) error
)

// OrderOption defines the ordering options for the ModelTokenDailyLimitConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByDailyLimitTokens orders the results by the daily_limit_tokens field.
func ByDailyLimitTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyLimitTokens, opts...).ToFunc()
}
