// Code generated by ent, DO NOT EDIT.

package tokenstatprojectionmetric

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectionID applies equality check predicate on the "projection_id" field. It's identical to ProjectionIDEQ.
func ProjectionID(v int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldProjectionID, v))
}

// MetricCode applies equality check predicate on the "metric_code" field. It's identical to MetricCodeEQ.
func MetricCode(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldMetricCode, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldStatus, v))
}

// EnabledAt applies equality check predicate on the "enabled_at" field. It's identical to EnabledAtEQ.
func EnabledAt(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldEnabledAt, v))
}

// DisabledAt applies equality check predicate on the "disabled_at" field. It's identical to DisabledAtEQ.
func DisabledAt(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldDisabledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProjectionIDEQ applies the EQ predicate on the "projection_id" field.
func ProjectionIDEQ(v int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldProjectionID, v))
}

// ProjectionIDNEQ applies the NEQ predicate on the "projection_id" field.
func ProjectionIDNEQ(v int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNEQ(FieldProjectionID, v))
}

// ProjectionIDIn applies the In predicate on the "projection_id" field.
func ProjectionIDIn(vs ...int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIn(FieldProjectionID, vs...))
}

// ProjectionIDNotIn applies the NotIn predicate on the "projection_id" field.
func ProjectionIDNotIn(vs ...int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotIn(FieldProjectionID, vs...))
}

// ProjectionIDGT applies the GT predicate on the "projection_id" field.
func ProjectionIDGT(v int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGT(FieldProjectionID, v))
}

// ProjectionIDGTE applies the GTE predicate on the "projection_id" field.
func ProjectionIDGTE(v int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGTE(FieldProjectionID, v))
}

// ProjectionIDLT applies the LT predicate on the "projection_id" field.
func ProjectionIDLT(v int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLT(FieldProjectionID, v))
}

// ProjectionIDLTE applies the LTE predicate on the "projection_id" field.
func ProjectionIDLTE(v int64) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLTE(FieldProjectionID, v))
}

// MetricCodeEQ applies the EQ predicate on the "metric_code" field.
func MetricCodeEQ(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldMetricCode, v))
}

// MetricCodeNEQ applies the NEQ predicate on the "metric_code" field.
func MetricCodeNEQ(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNEQ(FieldMetricCode, v))
}

// MetricCodeIn applies the In predicate on the "metric_code" field.
func MetricCodeIn(vs ...string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIn(FieldMetricCode, vs...))
}

// MetricCodeNotIn applies the NotIn predicate on the "metric_code" field.
func MetricCodeNotIn(vs ...string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotIn(FieldMetricCode, vs...))
}

// MetricCodeGT applies the GT predicate on the "metric_code" field.
func MetricCodeGT(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGT(FieldMetricCode, v))
}

// MetricCodeGTE applies the GTE predicate on the "metric_code" field.
func MetricCodeGTE(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGTE(FieldMetricCode, v))
}

// MetricCodeLT applies the LT predicate on the "metric_code" field.
func MetricCodeLT(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLT(FieldMetricCode, v))
}

// MetricCodeLTE applies the LTE predicate on the "metric_code" field.
func MetricCodeLTE(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLTE(FieldMetricCode, v))
}

// MetricCodeContains applies the Contains predicate on the "metric_code" field.
func MetricCodeContains(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldContains(FieldMetricCode, v))
}

// MetricCodeHasPrefix applies the HasPrefix predicate on the "metric_code" field.
func MetricCodeHasPrefix(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldHasPrefix(FieldMetricCode, v))
}

// MetricCodeHasSuffix applies the HasSuffix predicate on the "metric_code" field.
func MetricCodeHasSuffix(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldHasSuffix(FieldMetricCode, v))
}

// MetricCodeEqualFold applies the EqualFold predicate on the "metric_code" field.
func MetricCodeEqualFold(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEqualFold(FieldMetricCode, v))
}

// MetricCodeContainsFold applies the ContainsFold predicate on the "metric_code" field.
func MetricCodeContainsFold(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldContainsFold(FieldMetricCode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldContainsFold(FieldStatus, v))
}

// EnabledAtEQ applies the EQ predicate on the "enabled_at" field.
func EnabledAtEQ(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldEnabledAt, v))
}

// EnabledAtNEQ applies the NEQ predicate on the "enabled_at" field.
func EnabledAtNEQ(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNEQ(FieldEnabledAt, v))
}

// EnabledAtIn applies the In predicate on the "enabled_at" field.
func EnabledAtIn(vs ...time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIn(FieldEnabledAt, vs...))
}

// EnabledAtNotIn applies the NotIn predicate on the "enabled_at" field.
func EnabledAtNotIn(vs ...time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotIn(FieldEnabledAt, vs...))
}

// EnabledAtGT applies the GT predicate on the "enabled_at" field.
func EnabledAtGT(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGT(FieldEnabledAt, v))
}

// EnabledAtGTE applies the GTE predicate on the "enabled_at" field.
func EnabledAtGTE(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGTE(FieldEnabledAt, v))
}

// EnabledAtLT applies the LT predicate on the "enabled_at" field.
func EnabledAtLT(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLT(FieldEnabledAt, v))
}

// EnabledAtLTE applies the LTE predicate on the "enabled_at" field.
func EnabledAtLTE(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLTE(FieldEnabledAt, v))
}

// EnabledAtIsNil applies the IsNil predicate on the "enabled_at" field.
func EnabledAtIsNil() predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIsNull(FieldEnabledAt))
}

// EnabledAtNotNil applies the NotNil predicate on the "enabled_at" field.
func EnabledAtNotNil() predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotNull(FieldEnabledAt))
}

// DisabledAtEQ applies the EQ predicate on the "disabled_at" field.
func DisabledAtEQ(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldEQ(FieldDisabledAt, v))
}

// DisabledAtNEQ applies the NEQ predicate on the "disabled_at" field.
func DisabledAtNEQ(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNEQ(FieldDisabledAt, v))
}

// DisabledAtIn applies the In predicate on the "disabled_at" field.
func DisabledAtIn(vs ...time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIn(FieldDisabledAt, vs...))
}

// DisabledAtNotIn applies the NotIn predicate on the "disabled_at" field.
func DisabledAtNotIn(vs ...time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotIn(FieldDisabledAt, vs...))
}

// DisabledAtGT applies the GT predicate on the "disabled_at" field.
func DisabledAtGT(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGT(FieldDisabledAt, v))
}

// DisabledAtGTE applies the GTE predicate on the "disabled_at" field.
func DisabledAtGTE(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldGTE(FieldDisabledAt, v))
}

// DisabledAtLT applies the LT predicate on the "disabled_at" field.
func DisabledAtLT(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLT(FieldDisabledAt, v))
}

// DisabledAtLTE applies the LTE predicate on the "disabled_at" field.
func DisabledAtLTE(v time.Time) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldLTE(FieldDisabledAt, v))
}

// DisabledAtIsNil applies the IsNil predicate on the "disabled_at" field.
func DisabledAtIsNil() predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldIsNull(FieldDisabledAt))
}

// DisabledAtNotNil applies the NotNil predicate on the "disabled_at" field.
func DisabledAtNotNil() predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.FieldNotNull(FieldDisabledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TokenStatProjectionMetric) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TokenStatProjectionMetric) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TokenStatProjectionMetric) predicate.TokenStatProjectionMetric {
	return predicate.TokenStatProjectionMetric(sql.NotPredicates(p))
}
