// Code generated by ent, DO NOT EDIT.

package tokenstatperiodstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldUpdatedAt, v))
}

// PeriodType applies equality check predicate on the "period_type" field. It's identical to PeriodTypeEQ.
func PeriodType(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldPeriodType, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldPeriodEnd, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldState, v))
}

// FinalSyncVersion applies equality check predicate on the "final_sync_version" field. It's identical to FinalSyncVersionEQ.
func FinalSyncVersion(v int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldFinalSyncVersion, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldClosedAt, v))
}

// PersistedAt applies equality check predicate on the "persisted_at" field. It's identical to PersistedAtEQ.
func PersistedAt(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldPersistedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldDeletedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldUpdatedAt, v))
}

// PeriodTypeEQ applies the EQ predicate on the "period_type" field.
func PeriodTypeEQ(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldPeriodType, v))
}

// PeriodTypeNEQ applies the NEQ predicate on the "period_type" field.
func PeriodTypeNEQ(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldPeriodType, v))
}

// PeriodTypeIn applies the In predicate on the "period_type" field.
func PeriodTypeIn(vs ...string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldPeriodType, vs...))
}

// PeriodTypeNotIn applies the NotIn predicate on the "period_type" field.
func PeriodTypeNotIn(vs ...string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldPeriodType, vs...))
}

// PeriodTypeGT applies the GT predicate on the "period_type" field.
func PeriodTypeGT(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldPeriodType, v))
}

// PeriodTypeGTE applies the GTE predicate on the "period_type" field.
func PeriodTypeGTE(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldPeriodType, v))
}

// PeriodTypeLT applies the LT predicate on the "period_type" field.
func PeriodTypeLT(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldPeriodType, v))
}

// PeriodTypeLTE applies the LTE predicate on the "period_type" field.
func PeriodTypeLTE(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldPeriodType, v))
}

// PeriodTypeContains applies the Contains predicate on the "period_type" field.
func PeriodTypeContains(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldContains(FieldPeriodType, v))
}

// PeriodTypeHasPrefix applies the HasPrefix predicate on the "period_type" field.
func PeriodTypeHasPrefix(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldHasPrefix(FieldPeriodType, v))
}

// PeriodTypeHasSuffix applies the HasSuffix predicate on the "period_type" field.
func PeriodTypeHasSuffix(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldHasSuffix(FieldPeriodType, v))
}

// PeriodTypeEqualFold applies the EqualFold predicate on the "period_type" field.
func PeriodTypeEqualFold(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEqualFold(FieldPeriodType, v))
}

// PeriodTypeContainsFold applies the ContainsFold predicate on the "period_type" field.
func PeriodTypeContainsFold(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldContainsFold(FieldPeriodType, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldPeriodEnd, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldContainsFold(FieldState, v))
}

// FinalSyncVersionEQ applies the EQ predicate on the "final_sync_version" field.
func FinalSyncVersionEQ(v int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldFinalSyncVersion, v))
}

// FinalSyncVersionNEQ applies the NEQ predicate on the "final_sync_version" field.
func FinalSyncVersionNEQ(v int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldFinalSyncVersion, v))
}

// FinalSyncVersionIn applies the In predicate on the "final_sync_version" field.
func FinalSyncVersionIn(vs ...int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldFinalSyncVersion, vs...))
}

// FinalSyncVersionNotIn applies the NotIn predicate on the "final_sync_version" field.
func FinalSyncVersionNotIn(vs ...int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldFinalSyncVersion, vs...))
}

// FinalSyncVersionGT applies the GT predicate on the "final_sync_version" field.
func FinalSyncVersionGT(v int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldFinalSyncVersion, v))
}

// FinalSyncVersionGTE applies the GTE predicate on the "final_sync_version" field.
func FinalSyncVersionGTE(v int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldFinalSyncVersion, v))
}

// FinalSyncVersionLT applies the LT predicate on the "final_sync_version" field.
func FinalSyncVersionLT(v int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldFinalSyncVersion, v))
}

// FinalSyncVersionLTE applies the LTE predicate on the "final_sync_version" field.
func FinalSyncVersionLTE(v int64) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldFinalSyncVersion, v))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotNull(FieldClosedAt))
}

// PersistedAtEQ applies the EQ predicate on the "persisted_at" field.
func PersistedAtEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldPersistedAt, v))
}

// PersistedAtNEQ applies the NEQ predicate on the "persisted_at" field.
func PersistedAtNEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldPersistedAt, v))
}

// PersistedAtIn applies the In predicate on the "persisted_at" field.
func PersistedAtIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldPersistedAt, vs...))
}

// PersistedAtNotIn applies the NotIn predicate on the "persisted_at" field.
func PersistedAtNotIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldPersistedAt, vs...))
}

// PersistedAtGT applies the GT predicate on the "persisted_at" field.
func PersistedAtGT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldPersistedAt, v))
}

// PersistedAtGTE applies the GTE predicate on the "persisted_at" field.
func PersistedAtGTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldPersistedAt, v))
}

// PersistedAtLT applies the LT predicate on the "persisted_at" field.
func PersistedAtLT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldPersistedAt, v))
}

// PersistedAtLTE applies the LTE predicate on the "persisted_at" field.
func PersistedAtLTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldPersistedAt, v))
}

// PersistedAtIsNil applies the IsNil predicate on the "persisted_at" field.
func PersistedAtIsNil() predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIsNull(FieldPersistedAt))
}

// PersistedAtNotNil applies the NotNil predicate on the "persisted_at" field.
func PersistedAtNotNil() predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotNull(FieldPersistedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotNull(FieldDeletedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.FieldContainsFold(FieldLastError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TokenStatPeriodState) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TokenStatPeriodState) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TokenStatPeriodState) predicate.TokenStatPeriodState {
	return predicate.TokenStatPeriodState(sql.NotPredicates(p))
}
